/**
 * useAspectRatioVariants Hook Tests
 *
 * Tests for the hook managing aspect ratio variants,
 * auto-generation, and switching between ratios.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useAspectRatioVariants } from '../useAspectRatioVariants';
import type { FabricCanvasJSON, AspectRatioKey, SafeZone } from '../../types';

// Helper to create mock canvas JSON
function createMockCanvasJson(
  width = 1080,
  height = 1080,
  objects: Array<{ left: number; top: number; scaleX: number; scaleY: number }> = []
): FabricCanvasJSON {
  return {
    version: '6.0.0',
    objects: objects.map((obj, i) => ({
      type: 'rect',
      version: '6.0.0',
      left: obj.left,
      top: obj.top,
      width: 100,
      height: 100,
      scaleX: obj.scaleX,
      scaleY: obj.scaleY,
      name: `Object ${i + 1}`,
    })),
    width,
    height,
  };
}

// Helper to create variant data
function createVariantData(canvasJson: FabricCanvasJSON, isAutoGenerated = false) {
  return {
    canvasJson,
    isAutoGenerated,
    safeZone: { top: 5, right: 5, bottom: 5, left: 5 } as SafeZone,
  };
}

describe('useAspectRatioVariants', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Initialization', () => {
    it('initializes with primary ratio as current ratio', () => {
      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas: createMockCanvasJson(),
        })
      );

      expect(result.current.currentRatio).toBe('1:1');
    });

    it('initializes with empty variants when none provided', () => {
      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas: createMockCanvasJson(),
        })
      );

      expect(result.current.variants.size).toBe(0);
    });

    it('initializes with provided variants', () => {
      const initialVariants = new Map<AspectRatioKey, {
        canvasJson: FabricCanvasJSON;
        isAutoGenerated: boolean;
        thumbnailUrl?: string;
        safeZone: SafeZone;
      }>([
        ['16:9', createVariantData(createMockCanvasJson(1920, 1080), true)],
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas: createMockCanvasJson(),
          initialVariants,
        })
      );

      expect(result.current.variants.size).toBe(1);
      expect(result.current.variants.has('16:9')).toBe(true);
    });
  });

  describe('setCurrentRatio', () => {
    it('changes the current ratio', () => {
      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas: createMockCanvasJson(),
        })
      );

      act(() => {
        result.current.setCurrentRatio('16:9');
      });

      expect(result.current.currentRatio).toBe('16:9');
    });

    it('can switch to any supported ratio', () => {
      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas: createMockCanvasJson(),
        })
      );

      const ratios: AspectRatioKey[] = ['1:1', '16:9', '4:3', '9:16'];

      for (const ratio of ratios) {
        act(() => {
          result.current.setCurrentRatio(ratio);
        });
        expect(result.current.currentRatio).toBe(ratio);
      }
    });
  });

  describe('generateVariant', () => {
    it('returns null when no primary canvas', () => {
      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas: null,
        })
      );

      const generated = result.current.generateVariant('16:9');
      expect(generated).toBeNull();
    });

    it('generates variant with correct dimensions for wider ratio', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080, [
        { left: 100, top: 100, scaleX: 1, scaleY: 1 },
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('16:9');

      expect(generated).not.toBeNull();
      // 16:9 from 1:1 (1080x1080) should maintain width and reduce height
      expect(generated!.width).toBe(1080);
      expect(generated!.height).toBe(608); // 1080 / (16/9) rounded
    });

    it('generates variant with correct dimensions for taller ratio', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080, [
        { left: 100, top: 100, scaleX: 1, scaleY: 1 },
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('9:16');

      expect(generated).not.toBeNull();
      // 9:16 from 1:1 (1080x1080) should maintain height and reduce width
      expect(generated!.height).toBe(1080);
      expect(generated!.width).toBe(608); // 1080 * (9/16) rounded
    });

    it('scales objects proportionally', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080, [
        { left: 540, top: 540, scaleX: 2, scaleY: 2 }, // Center of canvas
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('16:9');

      expect(generated).not.toBeNull();
      expect(generated!.objects.length).toBe(1);

      const scaledObject = generated!.objects[0];
      // Scale should be applied (scale factor is min of width/height ratios)
      const scaleFactor = Math.min(1080 / 1080, 608 / 1080);
      expect(scaledObject.left).toBeCloseTo(540 * scaleFactor);
      expect(scaledObject.top).toBeCloseTo(540 * scaleFactor);
    });

    it('preserves all objects in generated variant', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080, [
        { left: 100, top: 100, scaleX: 1, scaleY: 1 },
        { left: 200, top: 200, scaleX: 1.5, scaleY: 1.5 },
        { left: 300, top: 300, scaleX: 0.5, scaleY: 0.5 },
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('4:3');

      expect(generated).not.toBeNull();
      expect(generated!.objects.length).toBe(3);
    });
  });

  describe('autoGenerateVariant', () => {
    it('generates and stores variant', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.autoGenerateVariant('16:9');
      });

      expect(result.current.variants.has('16:9')).toBe(true);
    });

    it('marks generated variant as auto-generated', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.autoGenerateVariant('16:9');
      });

      const variant = result.current.variants.get('16:9');
      expect(variant?.isAutoGenerated).toBe(true);
    });

    it('sets default safe zone', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.autoGenerateVariant('16:9');
      });

      const variant = result.current.variants.get('16:9');
      expect(variant?.safeZone).toEqual({ top: 5, right: 5, bottom: 5, left: 5 });
    });

    it('calls onVariantChange callback', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);
      const onVariantChange = vi.fn();

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
          onVariantChange,
        })
      );

      act(() => {
        result.current.autoGenerateVariant('16:9');
      });

      expect(onVariantChange).toHaveBeenCalledWith('16:9', expect.objectContaining({
        isAutoGenerated: true,
      }));
    });

    it('returns the generated canvas JSON', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      let generated: FabricCanvasJSON | null = null;
      act(() => {
        generated = result.current.autoGenerateVariant('16:9');
      });

      expect(generated).not.toBeNull();
      expect(generated!.width).toBeDefined();
      expect(generated!.height).toBeDefined();
    });
  });

  describe('setVariant', () => {
    it('stores a variant for a given ratio', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);
      const variantCanvas = createMockCanvasJson(1920, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.setVariant('16:9', {
          canvasJson: variantCanvas,
          isAutoGenerated: false,
        });
      });

      expect(result.current.variants.has('16:9')).toBe(true);
      expect(result.current.variants.get('16:9')?.canvasJson).toEqual(variantCanvas);
    });

    it('overwrites existing variant', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);
      const variantCanvas1 = createMockCanvasJson(1920, 1080);
      const variantCanvas2 = createMockCanvasJson(1920, 1080, [
        { left: 500, top: 500, scaleX: 1, scaleY: 1 },
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.setVariant('16:9', { canvasJson: variantCanvas1 });
      });

      act(() => {
        result.current.setVariant('16:9', { canvasJson: variantCanvas2 });
      });

      expect(result.current.variants.get('16:9')?.canvasJson.objects.length).toBe(1);
    });

    it('can set custom safe zone', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);
      const variantCanvas = createMockCanvasJson(1920, 1080);
      const customSafeZone: SafeZone = { top: 10, right: 5, bottom: 15, left: 5 };

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.setVariant('16:9', {
          canvasJson: variantCanvas,
          safeZone: customSafeZone,
        });
      });

      expect(result.current.variants.get('16:9')?.safeZone).toEqual(customSafeZone);
    });
  });

  describe('markAsManuallyEdited', () => {
    it('changes auto-generated variant to manual', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.autoGenerateVariant('16:9');
      });

      expect(result.current.variants.get('16:9')?.isAutoGenerated).toBe(true);

      act(() => {
        result.current.markAsManuallyEdited('16:9');
      });

      expect(result.current.variants.get('16:9')?.isAutoGenerated).toBe(false);
    });

    it('does nothing for non-existent variant', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const beforeSize = result.current.variants.size;

      act(() => {
        result.current.markAsManuallyEdited('16:9');
      });

      expect(result.current.variants.size).toBe(beforeSize);
    });
  });

  describe('resetToAutoGenerated', () => {
    it('regenerates variant from primary canvas', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);
      const manualCanvas = createMockCanvasJson(1920, 1080, [
        { left: 999, top: 999, scaleX: 5, scaleY: 5 },
      ]);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      // Set a manual variant
      act(() => {
        result.current.setVariant('16:9', {
          canvasJson: manualCanvas,
          isAutoGenerated: false,
        });
      });

      expect(result.current.variants.get('16:9')?.canvasJson.objects.length).toBe(1);

      // Reset to auto-generated
      act(() => {
        result.current.resetToAutoGenerated('16:9');
      });

      // Should be regenerated (empty objects from primary)
      expect(result.current.variants.get('16:9')?.canvasJson.objects.length).toBe(0);
      expect(result.current.variants.get('16:9')?.isAutoGenerated).toBe(true);
    });
  });

  describe('getVariantCanvas', () => {
    it('returns primary canvas for primary ratio', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const canvas = result.current.getVariantCanvas('1:1');
      expect(canvas).toEqual(primaryCanvas);
    });

    it('returns variant canvas for non-primary ratio', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);
      const variantCanvas = createMockCanvasJson(1920, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      act(() => {
        result.current.setVariant('16:9', { canvasJson: variantCanvas });
      });

      const canvas = result.current.getVariantCanvas('16:9');
      expect(canvas).toEqual(variantCanvas);
    });

    it('returns null for non-existent variant', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const canvas = result.current.getVariantCanvas('16:9');
      expect(canvas).toBeNull();
    });
  });

  describe('Edge Cases', () => {
    it('handles generating same ratio as primary', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('1:1');

      // Same ratio should produce same dimensions
      expect(generated).not.toBeNull();
      expect(generated!.width).toBe(1080);
      expect(generated!.height).toBe(1080);
    });

    it('handles canvas with no objects', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080, []);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('16:9');

      expect(generated).not.toBeNull();
      expect(generated!.objects.length).toBe(0);
    });

    it('preserves canvas version in generated variant', () => {
      const primaryCanvas = createMockCanvasJson(1080, 1080);

      const { result } = renderHook(() =>
        useAspectRatioVariants({
          primaryRatio: '1:1',
          primaryCanvas,
        })
      );

      const generated = result.current.generateVariant('16:9');

      expect(generated?.version).toBe('6.0.0');
    });
  });
});
