'use client';

import { useCallback } from 'react';
import { Star, Sparkles, Pencil } from 'lucide-react';
import { useCanvas } from './CanvasContext';
import { ASPECT_RATIOS, type AspectRatioKey } from './types';
import styles from './AspectRatioPanel.module.css';

/**
 * Variant status data for display
 */
interface VariantStatus {
  isAutoGenerated: boolean;
  thumbnailUrl?: string;
}

/**
 * AspectRatioPanel Props
 */
export interface AspectRatioPanelProps {
  /** The primary/source aspect ratio */
  primaryRatio: AspectRatioKey;
  /** Map of ratios to their variant status */
  variants: Map<AspectRatioKey, VariantStatus>;
  /** Callback when a ratio is selected */
  onRatioSelect: (ratio: AspectRatioKey) => void;
  /** Callback when generate button is clicked */
  onGenerateVariant: (ratio: AspectRatioKey) => void;
  /** Additional CSS class name */
  className?: string;
}

/**
 * Ratio option configuration
 */
interface RatioOption {
  id: AspectRatioKey;
  label: string;
  dimensions: string;
}

/**
 * Available aspect ratio options - derived from canonical ASPECT_RATIOS
 */
const RATIO_OPTIONS: RatioOption[] = (
  Object.entries(ASPECT_RATIOS) as [AspectRatioKey, (typeof ASPECT_RATIOS)[AspectRatioKey]][]
).map(([id, config]) => ({
  id,
  label: config.label,
  dimensions: `${config.width}x${config.height}`,
}));

/**
 * AspectRatioPanel - Panel for selecting and managing aspect ratio variants
 *
 * Features:
 * - Grid of ratio options with preview thumbnails
 * - Primary ratio indicator (star icon)
 * - Auto-generated vs manually edited badges
 * - Generate button for creating new variants
 * - Click to switch between ratios
 *
 * @example
 * ```tsx
 * <AspectRatioPanel
 *   primaryRatio="1:1"
 *   variants={new Map([['1:1', { isAutoGenerated: false }]])}
 *   onRatioSelect={(ratio) => console.log('Selected:', ratio)}
 *   onGenerateVariant={(ratio) => console.log('Generate:', ratio)}
 * />
 * ```
 */
export function AspectRatioPanel({
  primaryRatio,
  variants,
  onRatioSelect,
  onGenerateVariant,
  className,
}: AspectRatioPanelProps) {
  const { aspectRatio: currentRatio } = useCanvas();

  /**
   * Handle ratio card click
   */
  const handleRatioClick = useCallback((ratio: AspectRatioKey) => {
    onRatioSelect(ratio);
  }, [onRatioSelect]);

  /**
   * Handle generate button click
   */
  const handleGenerateClick = useCallback((
    event: React.MouseEvent,
    ratio: AspectRatioKey
  ) => {
    event.stopPropagation();
    onGenerateVariant(ratio);
  }, [onGenerateVariant]);

  /**
   * Handle keyboard navigation on ratio card
   */
  const handleKeyDown = useCallback((
    event: React.KeyboardEvent,
    ratio: AspectRatioKey
  ) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      onRatioSelect(ratio);
    }
  }, [onRatioSelect]);

  return (
    <div className={`${styles.panel} ${className ?? ''}`}>
      <div className={styles.header}>
        <h3 className={styles.title}>Aspect Ratios</h3>
      </div>
      <div className={styles.ratioGrid}>
        {RATIO_OPTIONS.map((option) => {
          const variant = variants.get(option.id);
          const isPrimary = option.id === primaryRatio;
          const isSelected = option.id === currentRatio;
          const hasVariant = !!variant;
          const showGenerateButton = !hasVariant && option.id !== primaryRatio;

          return (
            <div
              key={option.id}
              className={styles.ratioCard}
            >
              {/* Main ratio button - handles selection */}
              <button
                type="button"
                className={`${styles.ratioButton} ${isSelected ? styles.selected : ''}`}
                onClick={() => handleRatioClick(option.id)}
                onKeyDown={(e) => handleKeyDown(e, option.id)}
                data-selected={isSelected}
                aria-pressed={isSelected}
              >
                <div
                  className={styles.ratioPreview}
                  style={{ aspectRatio: option.id.replace(':', '/') }}
                >
                  {variant?.thumbnailUrl ? (
                    <img
                      src={variant.thumbnailUrl}
                      alt={option.label}
                      className={styles.thumbnailImage}
                    />
                  ) : (
                    <span className={styles.placeholder}>{option.id}</span>
                  )}
                </div>
                <div className={styles.ratioInfo}>
                  <span className={styles.ratioLabel}>
                    {isPrimary && (
                      <span className={styles.primaryBadge} title="Primary ratio">
                        <Star size={10} fill="currentColor" />
                      </span>
                    )}
                    {option.label}
                  </span>
                  <span className={styles.ratioDimensions}>{option.dimensions}</span>
                  {hasVariant && (
                    <span
                      className={variant.isAutoGenerated ? styles.autoBadge : styles.manualBadge}
                      title={variant.isAutoGenerated ? 'Auto-generated from primary' : 'Manually edited'}
                    >
                      {variant.isAutoGenerated ? (
                        <>
                          <Sparkles size={10} />
                          Auto
                        </>
                      ) : (
                        <>
                          <Pencil size={10} />
                          Manual
                        </>
                      )}
                    </span>
                  )}
                </div>
              </button>

              {/* Generate button - separate from ratio button to avoid nesting */}
              {showGenerateButton && (
                <button
                  type="button"
                  className={styles.generateButton}
                  onClick={(e) => handleGenerateClick(e, option.id)}
                  aria-label={`Generate ${option.label} variant`}
                >
                  Generate
                </button>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default AspectRatioPanel;
