// Data Sources
export {
  dataSources,
  dataRows,
  columnMappings,
  dataSourcesRelations,
  dataRowsRelations,
  columnMappingsRelations,
  dataSourceTypeEnum,
} from "./data-sources.js";
export type {
  DataSource,
  NewDataSource,
  DataRow,
  NewDataRow,
  ColumnMapping,
  NewColumnMapping,
  ApiKeyConfig,
  DataSourceConfig,
  SyncFrequency,
  SyncStatus,
  ApiAuthType,
  JsonFlattenConfig,
  ApiFetchConfig,
  GoogleSheetsConfig,
  ColumnLengthStat,
  ColumnLengthStats,
} from "./data-sources.js";

// Campaign Templates
export {
  campaignTemplates,
  adGroupTemplates,
  adTemplates,
  campaignTemplatesRelations,
  adGroupTemplatesRelations,
  adTemplatesRelations,
  platformEnum,
} from "./campaign-templates.js";
export type {
  CampaignTemplate,
  NewCampaignTemplate,
  CampaignStructure,
  AdGroupTemplate,
  NewAdGroupTemplate,
  AdGroupSettings,
  AdTemplate,
  NewAdTemplate,
  AdTemplateVariables,
} from "./campaign-templates.js";

// Rules
export {
  rules,
  templateRules,
  rulesRelations,
  templateRulesRelations,
  ruleTypeEnum,
} from "./rules.js";
export type {
  Rule,
  NewRule,
  RuleCondition,
  RuleAction,
  TemplateRule,
  NewTemplateRule,
} from "./rules.js";

// Generated Campaigns
export {
  generatedCampaigns,
  syncRecords,
  generatedCampaignsRelations,
  syncRecordsRelations,
  campaignStatusEnum,
  syncStatusEnum,
} from "./generated-campaigns.js";
export type {
  GeneratedCampaign,
  NewGeneratedCampaign,
  GeneratedCampaignData,
  SyncRecord,
  NewSyncRecord,
} from "./generated-campaigns.js";

// Ad Accounts
export {
  adAccounts,
  oauthTokens,
  adAccountsRelations,
  oauthTokensRelations,
  accountStatusEnum,
} from "./ad-accounts.js";
export type {
  AdAccount,
  NewAdAccount,
  OAuthToken,
  NewOAuthToken,
} from "./ad-accounts.js";

// Asset Folders (folder-based organization for creatives)
export {
  assetFolders,
  assetFolderRelations,
} from "./asset-folders.js";
export type { AssetFolder, NewAssetFolder } from "./asset-folders.js";

// Creatives
export {
  creatives,
  creativeTags,
  creativeTemplateLinks,
  creativesRelations,
  creativeTagsRelations,
  creativeTemplateLinksRelations,
  creativeTypeEnum,
  creativeStatusEnum,
} from "./creatives.js";
export type {
  Creative,
  NewCreative,
  CreativeTag,
  NewCreativeTag,
  CreativeTemplateLink,
  NewCreativeTemplateLink,
  CreativeDimensions,
  CreativeMetadata,
  CreativeSelectionCondition,
} from "./creatives.js";

// Transforms
export { transforms, transformsRelations } from "./transforms.js";
export type {
  Transform,
  NewTransform,
  TransformConfig,
  AggregationConfig,
  AggregationFunction,
} from "./transforms.js";

// Campaign Sets
export {
  campaignSets,
  campaignSetsRelations,
  campaignSetStatusEnum,
  campaignSetSyncStatusEnum,
} from "./campaign-sets.js";
export type {
  CampaignSet,
  NewCampaignSet,
  CampaignSetConfig,
} from "./campaign-sets.js";

// Ad Groups (normalized from JSONB)
export {
  adGroups,
  adGroupsRelations,
  adGroupStatusEnum,
} from "./ad-groups.js";
export type {
  AdGroup,
  NewAdGroup,
  AdGroupSettings as NormalizedAdGroupSettings,
} from "./ad-groups.js";

// Ads
export { ads, adsRelations, adStatusEnum } from "./ads.js";
export type { Ad, NewAd, AdAssets } from "./ads.js";

// Keywords
export {
  keywords,
  keywordsRelations,
  keywordMatchTypeEnum,
  keywordStatusEnum,
} from "./keywords.js";
export type { Keyword, NewKeyword } from "./keywords.js";

// User OAuth Tokens (for data source integrations)
export { userOAuthTokens } from "./user-oauth-tokens.js";
export type {
  UserOAuthToken,
  NewUserOAuthToken,
} from "./user-oauth-tokens.js";

// Teams (multi-tenant workspaces)
export {
  teams,
  teamMemberships,
  teamInvitations,
  teamsRelations,
  teamMembershipsRelations,
  teamInvitationsRelations,
  teamRoleEnum,
  teamPlanEnum,
} from "./teams.js";
export type {
  Team,
  NewTeam,
  TeamMembership,
  NewTeamMembership,
  TeamInvitation,
  NewTeamInvitation,
  TeamSettings,
  TeamRole,
  TeamPlan,
} from "./teams.js";

// Better Auth (authentication)
// Generated by @better-auth/cli - provides user, session, account, verification tables
export {
  user,
  session,
  account,
  verification,
  userRelations,
  sessionRelations,
  accountRelations,
} from "./auth.js";
export type {
  User,
  NewUser,
  Session,
  NewSession,
  Account,
  NewAccount,
  Verification,
  NewVerification,
} from "./auth.js";

// Design Templates (Fabric.js canvas editor templates)
export {
  designTemplates,
  templateVariants,
  designTemplatesRelations,
  templateVariantsRelations,
  designTemplateStatusEnum,
} from "./design-templates.js";
export type {
  DesignTemplate,
  NewDesignTemplate,
  TemplateVariant,
  NewTemplateVariant,
  FabricCanvasJSON,
  FabricObject,
  FabricTextObject,
  FabricImageObject,
  TemplateVariable,
  SafeZone,
} from "./design-templates.js";

// Generated Creatives (server-side rendered images)
export {
  generatedCreatives,
  generatedCreativesRelations,
  generatedCreativeStatusEnum,
} from "./generated-creatives.js";
export type {
  GeneratedCreative,
  NewGeneratedCreative,
  VariableValuesSnapshot,
} from "./generated-creatives.js";

// Generation Jobs (batch image generation tracking)
export {
  generationJobs,
  generationJobsRelations,
  generationJobStatusEnum,
} from "./generation-jobs.js";
export type {
  GenerationJob,
  NewGenerationJob,
  AspectRatioSpec,
  RowFilter,
  GenerationError,
} from "./generation-jobs.js";

// Sync Validation Results (validation persistence)
export {
  syncValidationResults,
  syncValidationResultsRelations,
  validationStatusEnum,
  validationTriggerEnum,
} from "./sync-validation-results.js";
export type {
  SyncValidationResult,
  NewSyncValidationResult,
  StoredValidationError,
  StoredValidationSummary,
  ValidationErrorCode,
  ValidationEntityType,
} from "./sync-validation-results.js";
