/**
 * AspectRatioPanel Component Tests
 *
 * Tests for the aspect ratio selection panel showing available ratios,
 * variant status, and generation controls.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { AspectRatioPanel } from '../AspectRatioPanel';
import { CanvasProvider } from '../CanvasContext';
import type { AspectRatioKey } from '../types';

// Mock the CanvasContext
vi.mock('../CanvasContext', async () => {
  const actual = await vi.importActual('../CanvasContext');
  return {
    ...actual,
    useCanvas: () => ({
      aspectRatio: '1:1',
      canvas: null,
      selectedObjects: [],
      zoom: 1,
      canvasSize: { width: 1080, height: 1080 },
      isDirty: false,
      variables: [],
      activeTool: 'select',
      isLoading: false,
      error: null,
    }),
  };
});

// Helper to create variant data
function createVariantData(isAutoGenerated: boolean, thumbnailUrl?: string) {
  return { isAutoGenerated, thumbnailUrl };
}

// Default props factory
function createDefaultProps() {
  return {
    primaryRatio: '1:1' as AspectRatioKey,
    variants: new Map<AspectRatioKey, { isAutoGenerated: boolean; thumbnailUrl?: string }>([
      ['1:1', createVariantData(false)],
    ]),
    onRatioSelect: vi.fn(),
    onGenerateVariant: vi.fn(),
  };
}

function renderAspectRatioPanel(props = createDefaultProps()) {
  return render(
    <CanvasProvider>
      <AspectRatioPanel {...props} />
    </CanvasProvider>
  );
}

describe('AspectRatioPanel', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Rendering', () => {
    it('renders the panel with title', () => {
      renderAspectRatioPanel();
      expect(screen.getByText('Aspect Ratios')).toBeInTheDocument();
    });

    it('renders all ratio options', () => {
      renderAspectRatioPanel();
      expect(screen.getByText('Square')).toBeInTheDocument();
      expect(screen.getByText('Landscape')).toBeInTheDocument();
      expect(screen.getByText('Portrait/Story')).toBeInTheDocument();
      expect(screen.getByText('Standard')).toBeInTheDocument();
      expect(screen.getByText('Instagram Portrait')).toBeInTheDocument();
    });

    it('displays dimension info for each ratio', () => {
      renderAspectRatioPanel();
      expect(screen.getByText('1080x1080')).toBeInTheDocument(); // 1:1
      expect(screen.getByText('1920x1080')).toBeInTheDocument(); // 16:9
      expect(screen.getByText('1080x1920')).toBeInTheDocument(); // 9:16
      expect(screen.getByText('1440x1080')).toBeInTheDocument(); // 4:3
      expect(screen.getByText('1080x1350')).toBeInTheDocument(); // 4:5
    });

    it('applies custom className', () => {
      const { container } = renderAspectRatioPanel({
        ...createDefaultProps(),
        className: 'custom-class',
      });
      expect(container.querySelector('.custom-class')).toBeInTheDocument();
    });
  });

  describe('Primary Ratio Indicator', () => {
    it('shows star icon for primary ratio', () => {
      const { container } = renderAspectRatioPanel();
      // The primary ratio (1:1) should have a star badge
      const primaryBadge = container.querySelector('[class*="primaryBadge"]');
      expect(primaryBadge).toBeInTheDocument();
    });

    it('highlights the selected ratio', () => {
      renderAspectRatioPanel();
      // The 1:1 ratio button should have data-selected="true" (since aspectRatio is '1:1')
      const selectedButton = screen.getByRole('button', { pressed: true });
      expect(selectedButton).toBeInTheDocument();
    });
  });

  describe('Variant Status Badges', () => {
    it('shows Auto badge for auto-generated variants', () => {
      const props = createDefaultProps();
      props.variants.set('16:9', createVariantData(true));

      renderAspectRatioPanel(props);
      expect(screen.getByText('Auto')).toBeInTheDocument();
    });

    it('shows Manual badge for manually edited variants', () => {
      const props = createDefaultProps();
      props.variants.set('16:9', createVariantData(false));

      renderAspectRatioPanel(props);
      const manualBadges = screen.getAllByText('Manual');
      expect(manualBadges.length).toBeGreaterThan(0);
    });

    it('does not show badge for ratios without variants', () => {
      const props = createDefaultProps();
      // Only primary ratio has a variant

      renderAspectRatioPanel(props);
      // There should be no Auto badge (only Manual for the primary)
      expect(screen.queryByText('Auto')).not.toBeInTheDocument();
    });
  });

  describe('Generate Button', () => {
    it('shows Generate button for ratios without variants (except primary)', () => {
      renderAspectRatioPanel();
      // 16:9, 9:16, 4:3, and 4:5 should have Generate buttons
      const generateButtons = screen.getAllByText('Generate');
      expect(generateButtons.length).toBe(4); // All except primary (1:1)
    });

    it('does not show Generate button for primary ratio', () => {
      renderAspectRatioPanel();
      // Find the Square (1:1) section - it should not have a Generate button
      const squareSection = screen.getByText('Square').closest('button');
      expect(squareSection?.textContent).not.toContain('Generate');
    });

    it('does not show Generate button for ratios with existing variants', () => {
      const props = createDefaultProps();
      props.variants.set('16:9', createVariantData(true));

      renderAspectRatioPanel(props);
      // Now only 9:16, 4:3, and 4:5 should have Generate buttons
      const generateButtons = screen.getAllByText('Generate');
      expect(generateButtons.length).toBe(3);
    });

    it('calls onGenerateVariant when Generate button is clicked', () => {
      const props = createDefaultProps();
      renderAspectRatioPanel(props);

      const generateButtons = screen.getAllByText('Generate');
      fireEvent.click(generateButtons[0]);

      expect(props.onGenerateVariant).toHaveBeenCalled();
    });

    it('prevents ratio selection when clicking Generate button', () => {
      const props = createDefaultProps();
      renderAspectRatioPanel(props);

      // The stopPropagation should prevent onRatioSelect from being called
      // Test by verifying onGenerateVariant is called with the right ratio
      const generateButtons = screen.getAllByText('Generate');
      fireEvent.click(generateButtons[0]);

      // The first generate button should be for 16:9 (first non-primary ratio)
      expect(props.onGenerateVariant).toHaveBeenCalledWith('16:9');
    });
  });

  describe('Ratio Selection', () => {
    it('calls onRatioSelect when a ratio button is clicked', () => {
      const props = createDefaultProps();
      renderAspectRatioPanel(props);

      // Click on the Landscape (16:9) ratio
      const landscapeButton = screen.getByText('Landscape').closest('button');
      if (landscapeButton) {
        fireEvent.click(landscapeButton);
      }

      expect(props.onRatioSelect).toHaveBeenCalledWith('16:9');
    });

    it('can switch between different ratios', () => {
      const props = createDefaultProps();
      renderAspectRatioPanel(props);

      // Click on Standard (4:3)
      const standardButton = screen.getByText('Standard').closest('button');
      if (standardButton) {
        fireEvent.click(standardButton);
      }

      expect(props.onRatioSelect).toHaveBeenCalledWith('4:3');

      // Click on Portrait/Story (9:16)
      const portraitButton = screen.getByText('Portrait/Story').closest('button');
      if (portraitButton) {
        fireEvent.click(portraitButton);
      }

      expect(props.onRatioSelect).toHaveBeenCalledWith('9:16');
    });
  });

  describe('Thumbnail Preview', () => {
    it('shows placeholder when no thumbnail URL', () => {
      renderAspectRatioPanel();
      // Ratio placeholders should show the ratio string
      expect(screen.getAllByText('1:1').length).toBeGreaterThan(0);
    });

    it('shows image when thumbnail URL is provided', () => {
      const props = createDefaultProps();
      props.variants.set('1:1', createVariantData(false, 'https://example.com/thumb.png'));

      renderAspectRatioPanel(props);

      const img = screen.getByRole('img', { name: 'Square' });
      expect(img).toBeInTheDocument();
      expect(img).toHaveAttribute('src', 'https://example.com/thumb.png');
    });
  });

  describe('Accessibility', () => {
    it('ratio buttons are keyboard accessible', () => {
      renderAspectRatioPanel();

      const ratioButtons = screen.getAllByRole('button').filter(
        btn => !btn.textContent?.includes('Generate')
      );

      ratioButtons.forEach(button => {
        expect(button).not.toHaveAttribute('tabindex', '-1');
      });
    });

    it('generate buttons have accessible names', () => {
      renderAspectRatioPanel();

      const generateButtons = screen.getAllByRole('button', { name: /generate/i });
      generateButtons.forEach(button => {
        expect(button).toBeInTheDocument();
      });
    });
  });
});
