"use client";

import { useCallback, useRef, useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useTeam } from "@/lib/teams/context";
import { useDesignTemplate } from "@/lib/hooks/useDesignTemplates";
import {
  FabricCanvas,
  CanvasProvider,
  EditorToolbar,
  LayersPanel,
  PropertiesPanel,
  VariablesPanel,
  AspectRatioPanel,
  useCanvas,
  type FabricCanvasRef,
  type FabricCanvasJSON,
  type AspectRatioKey,
  ASPECT_RATIOS,
} from "@/components/canvas-editor";
import styles from "./page.module.css";

/**
 * Edit Template Page
 *
 * Full canvas editor layout with:
 * - Header with template name, save status, actions
 * - Left sidebar: Layers panel, Variables panel
 * - Center: Canvas workspace
 * - Right sidebar: Properties panel, Aspect ratio panel
 * - Auto-save with debounce
 */
export default function EditTemplatePage() {
  const params = useParams();
  const { currentTeam } = useTeam();
  const templateId = params.templateId as string;
  const teamSlug = params.teamSlug as string;
  const locale = params.locale as string;

  const { template, loading, error, fetchTemplate, updateTemplate } =
    useDesignTemplate(currentTeam?.id, templateId);

  // Fetch template on mount
  useEffect(() => {
    if (currentTeam?.id && templateId) {
      fetchTemplate();
    }
  }, [currentTeam?.id, templateId, fetchTemplate]);

  // Loading state
  if (loading && !template) {
    return (
      <div className={styles.loadingPage}>
        <div className={styles.spinner} />
        <span>Loading template...</span>
      </div>
    );
  }

  // Error state
  if (error && !template) {
    return (
      <div className={styles.errorPage}>
        <ErrorIcon />
        <h2>Failed to load template</h2>
        <p>{error}</p>
        <button onClick={() => fetchTemplate()} className={styles.retryButton}>
          Try Again
        </button>
        <Link
          href={`/${locale}/${teamSlug}/design-templates`}
          className={styles.backLink}
        >
          Back to Templates
        </Link>
      </div>
    );
  }

  // Not found state
  if (!template) {
    return (
      <div className={styles.notFoundPage}>
        <NotFoundIcon />
        <h2>Template not found</h2>
        <p>The template you&apos;re looking for doesn&apos;t exist or you don&apos;t have access.</p>
        <Link
          href={`/${locale}/${teamSlug}/design-templates`}
          className={styles.backLink}
        >
          Back to Templates
        </Link>
      </div>
    );
  }

  return (
    <CanvasProvider initialAspectRatio={template.primaryAspectRatio}>
      <TemplateEditor
        template={template}
        updateTemplate={updateTemplate}
        teamSlug={teamSlug}
        locale={locale}
      />
    </CanvasProvider>
  );
}

// ============================================================================
// TemplateEditor Component
// ============================================================================

interface TemplateEditorProps {
  template: {
    id: string;
    name: string;
    primaryAspectRatio: AspectRatioKey;
    canvasJson: FabricCanvasJSON;
    variants?: Array<{
      aspectRatio: AspectRatioKey;
      isAutoGenerated: boolean;
      thumbnailUrl?: string;
    }>;
  };
  updateTemplate: (input: { canvasJson?: FabricCanvasJSON; name?: string }) => Promise<unknown>;
  teamSlug: string;
  locale: string;
}

function TemplateEditor({
  template,
  updateTemplate,
  teamSlug,
  locale,
}: TemplateEditorProps) {
  const canvasRef = useRef<FabricCanvasRef>(null);
  const { canvasSize, isDirty, canvas, markDirty, markClean, setAspectRatio } = useCanvas();

  const [isSaving, setIsSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  // Auto-save debounce ref
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  /**
   * Handle canvas change - triggers auto-save with debounce
   */
  const handleCanvasChange = useCallback(
    (json: FabricCanvasJSON) => {
      markDirty();
      setSaveError(null);

      // Debounced auto-save (5 seconds)
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
      saveTimeoutRef.current = setTimeout(() => {
        handleSave(json);
      }, 5000);
    },
    [markDirty]
  );

  /**
   * Save the template
   */
  const handleSave = useCallback(
    async (json?: FabricCanvasJSON) => {
      const canvasJson = json ?? canvasRef.current?.getJson();
      if (!canvasJson) return;

      setIsSaving(true);
      setSaveError(null);

      try {
        await updateTemplate({ canvasJson });
        markClean();
        setLastSaved(new Date());
      } catch (err) {
        console.error("Failed to save template:", err);
        setSaveError(err instanceof Error ? err.message : "Failed to save");
      } finally {
        setIsSaving(false);
      }
    },
    [updateTemplate, markClean]
  );

  /**
   * Manual save - clears pending auto-save
   */
  const handleManualSave = useCallback(() => {
    // Clear any pending debounced save
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
      saveTimeoutRef.current = null;
    }
    return handleSave();
  }, [handleSave]);

  /**
   * Handle aspect ratio selection
   */
  const handleRatioSelect = useCallback(
    (ratio: AspectRatioKey) => {
      setAspectRatio(ratio);
    },
    [setAspectRatio]
  );

  /**
   * Handle variant generation (placeholder)
   */
  const handleGenerateVariant = useCallback((ratio: AspectRatioKey) => {
    console.log("Generate variant for:", ratio);
    // TODO: Implement variant generation
  }, []);

  // Build variants map for AspectRatioPanel
  const variantsMap = new Map<
    AspectRatioKey,
    { isAutoGenerated: boolean; thumbnailUrl?: string }
  >();
  template.variants?.forEach((v) => {
    variantsMap.set(v.aspectRatio, {
      isAutoGenerated: v.isAutoGenerated,
      thumbnailUrl: v.thumbnailUrl,
    });
  });
  // Always include primary ratio as "existing"
  if (!variantsMap.has(template.primaryAspectRatio)) {
    variantsMap.set(template.primaryAspectRatio, { isAutoGenerated: false });
  }

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, []);

  // Warn about unsaved changes on navigation
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty) {
        e.preventDefault();
        e.returnValue = "";
      }
    };

    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [isDirty]);

  return (
    <div className={styles.editor}>
      {/* Header */}
      <header className={styles.header}>
        <div className={styles.headerLeft}>
          <Link
            href={`/${locale}/${teamSlug}/design-templates`}
            className={styles.backButton}
            aria-label="Back to templates"
          >
            <BackIcon />
          </Link>
          <h1 className={styles.templateName}>{template.name}</h1>
          <span className={styles.aspectBadge}>{template.primaryAspectRatio}</span>
        </div>

        <div className={styles.headerCenter}>
          <div className={styles.saveStatus}>
            {isSaving && (
              <span className={styles.savingStatus}>
                <div className={styles.saveSpinner} />
                Saving...
              </span>
            )}
            {!isSaving && saveError && (
              <span className={styles.errorStatus}>
                <ErrorStatusIcon />
                {saveError}
              </span>
            )}
            {!isSaving && !saveError && isDirty && (
              <span className={styles.unsavedStatus}>Unsaved changes</span>
            )}
            {!isSaving && !saveError && !isDirty && lastSaved && (
              <span className={styles.savedStatus}>
                <CheckIcon />
                Saved {formatTime(lastSaved)}
              </span>
            )}
          </div>
        </div>

        <div className={styles.headerRight}>
          <EditorToolbar
            onSave={handleManualSave}
            isSaving={isSaving}
            saveDisabled={!isDirty}
          />
        </div>
      </header>

      {/* Main workspace */}
      <div className={styles.workspace}>
        {/* Left sidebar */}
        <aside className={styles.leftSidebar}>
          <LayersPanel className={styles.sidebarPanel} />
          <VariablesPanel className={styles.sidebarPanel} />
        </aside>

        {/* Canvas area */}
        <main className={styles.canvasArea}>
          <div className={styles.canvasContainer}>
            <FabricCanvas
              ref={canvasRef}
              initialJson={template.canvasJson}
              width={canvasSize.width}
              height={canvasSize.height}
              onChange={handleCanvasChange}
            />
          </div>
        </main>

        {/* Right sidebar */}
        <aside className={styles.rightSidebar}>
          <PropertiesPanel canvas={canvas} className={styles.sidebarPanel} />
          <AspectRatioPanel
            primaryRatio={template.primaryAspectRatio}
            variants={variantsMap}
            onRatioSelect={handleRatioSelect}
            onGenerateVariant={handleGenerateVariant}
            className={styles.sidebarPanel}
          />
        </aside>
      </div>
    </div>
  );
}

// ============================================================================
// Helper Functions
// ============================================================================

function formatTime(date: Date): string {
  const now = new Date();
  const diff = now.getTime() - date.getTime();

  if (diff < 60000) {
    return "just now";
  }

  return date.toLocaleTimeString(undefined, {
    hour: "numeric",
    minute: "2-digit",
  });
}

// ============================================================================
// Icon Components
// ============================================================================

function BackIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 15l-5-5 5-5" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 14 14"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 7.5l3 3 6-6" />
    </svg>
  );
}

function ErrorIcon() {
  return (
    <svg
      width="48"
      height="48"
      viewBox="0 0 48 48"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
    >
      <circle cx="24" cy="24" r="18" />
      <path d="M24 16v10" />
      <circle cx="24" cy="32" r="1" fill="currentColor" />
    </svg>
  );
}

function ErrorStatusIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 14 14"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
    >
      <circle cx="7" cy="7" r="5" />
      <path d="M7 4.5v3" />
      <circle cx="7" cy="9.5" r="0.5" fill="currentColor" />
    </svg>
  );
}

function NotFoundIcon() {
  return (
    <svg
      width="48"
      height="48"
      viewBox="0 0 48 48"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="6" y="6" width="36" height="36" rx="4" />
      <path d="M6 18h36" />
      <path d="M18 6v36" />
      <path d="M28 28l8 8" />
      <path d="M28 36l8-8" />
    </svg>
  );
}
