/**
 * Database seed script
 *
 * Seeds the database with the demo footwear catalog.
 * Run with: pnpm db:seed
 */

import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema/index.js";

const connectionString =
  process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/dotoro";

console.log("Connecting to database...");
const client = postgres(connectionString);
const db = drizzle(client, { schema });

// Helper to generate UUIDs consistently for foreign key relationships
const uuids = {
  // Data source
  dataSource1: "11111111-1111-1111-1111-111111111111",
};

// Helper to generate data row UUID from index
const dataRowUuid = (index: number) =>
  `00000000-0003-0000-0000-${String(index + 1).padStart(12, "0")}`;

// ============================================
// DEMO CATALOGUE FOOTWEAR - Realistic Product Feed
// ============================================
// A comprehensive athletic footwear catalog with:
// - SKU IDs, Product IDs, GTINs
// - Categories & Subcategories
// - Color variants with hex codes
// - Size ranges
// - Pricing (MSRP, sale prices)
// - Inventory status
// - Gender targeting
// - Rich descriptions
// ============================================

const demoCatalogueFootwear = [
  // ============================================
  // NIKE - Running
  // ============================================
  {
    sku: "NK-AM90-001-BLK-10",
    product_id: "NK-AM90-001",
    gtin: "194501234567",
    brand: "Nike",
    product_name: "Air Max 90",
    category: "Running",
    subcategory: "Road Running",
    color: "Black/White",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 130.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 45,
    condition: "new",
    material: "Mesh/Leather",
    weight_oz: 13.2,
    description: "The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle outsole, stitched overlays and classic TPU accents. Classic looks meet modern comfort.",
    short_description: "Iconic style with visible Air cushioning",
    final_url: "https://nike.com/t/air-max-90-mens-shoes/NK-AM90-001-BLK-10",
    image_url: "https://static.nike.com/a/images/air-max-90-black.jpg",
    additional_images: "https://static.nike.com/a/images/air-max-90-black-2.jpg,https://static.nike.com/a/images/air-max-90-black-3.jpg",
    tags: "bestseller,classic,lifestyle",
    age_group: "adult",
    shipping_weight_lb: 2.1,
  },
  {
    sku: "NK-AM90-001-WHT-10",
    product_id: "NK-AM90-001",
    gtin: "194501234568",
    brand: "Nike",
    product_name: "Air Max 90",
    category: "Running",
    subcategory: "Road Running",
    color: "White/White",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 130.00,
    sale_price: 104.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 28,
    condition: "new",
    material: "Mesh/Leather",
    weight_oz: 13.2,
    description: "The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle outsole, stitched overlays and classic TPU accents. Classic looks meet modern comfort.",
    short_description: "Iconic style with visible Air cushioning",
    final_url: "https://nike.com/t/air-max-90-mens-shoes/NK-AM90-001-WHT-10",
    image_url: "https://static.nike.com/a/images/air-max-90-white.jpg",
    additional_images: "https://static.nike.com/a/images/air-max-90-white-2.jpg",
    tags: "sale,classic,lifestyle",
    age_group: "adult",
    shipping_weight_lb: 2.1,
  },
  {
    sku: "NK-AM90-001-BLK-9",
    product_id: "NK-AM90-001",
    gtin: "194501234569",
    brand: "Nike",
    product_name: "Air Max 90",
    category: "Running",
    subcategory: "Road Running",
    color: "Black/White",
    color_hex: "#000000",
    size: "9",
    size_type: "US",
    gender: "Men",
    price: 130.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 32,
    condition: "new",
    material: "Mesh/Leather",
    weight_oz: 12.8,
    description: "The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle outsole, stitched overlays and classic TPU accents. Classic looks meet modern comfort.",
    short_description: "Iconic style with visible Air cushioning",
    final_url: "https://nike.com/t/air-max-90-mens-shoes/NK-AM90-001-BLK-9",
    image_url: "https://static.nike.com/a/images/air-max-90-black.jpg",
    additional_images: "https://static.nike.com/a/images/air-max-90-black-2.jpg",
    tags: "bestseller,classic",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "NK-PEG40-002-GRY-11",
    product_id: "NK-PEG40-002",
    gtin: "194501234601",
    brand: "Nike",
    product_name: "Pegasus 40",
    category: "Running",
    subcategory: "Road Running",
    color: "Wolf Grey/Black",
    color_hex: "#6B6B6B",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 67,
    condition: "new",
    material: "Engineered Mesh",
    weight_oz: 10.2,
    description: "A springy ride for every run. The Pegasus 40 continues to put a spring in your step with responsive React foam and Air Zoom units at the forefoot.",
    short_description: "Responsive cushioning for daily training",
    final_url: "https://nike.com/t/pegasus-40-mens-road-running/NK-PEG40-002-GRY-11",
    image_url: "https://static.nike.com/a/images/pegasus-40-grey.jpg",
    additional_images: "https://static.nike.com/a/images/pegasus-40-grey-2.jpg,https://static.nike.com/a/images/pegasus-40-grey-3.jpg",
    tags: "new-arrival,daily-trainer,neutral",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "NK-PEG40-002-BLU-10",
    product_id: "NK-PEG40-002",
    gtin: "194501234602",
    brand: "Nike",
    product_name: "Pegasus 40",
    category: "Running",
    subcategory: "Road Running",
    color: "Racer Blue/White",
    color_hex: "#0066CC",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: 119.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 41,
    condition: "new",
    material: "Engineered Mesh",
    weight_oz: 10.0,
    description: "A springy ride for every run. The Pegasus 40 continues to put a spring in your step with responsive React foam and Air Zoom units at the forefoot.",
    short_description: "Responsive cushioning for daily training",
    final_url: "https://nike.com/t/pegasus-40-mens-road-running/NK-PEG40-002-BLU-10",
    image_url: "https://static.nike.com/a/images/pegasus-40-blue.jpg",
    additional_images: "https://static.nike.com/a/images/pegasus-40-blue-2.jpg",
    tags: "sale,daily-trainer,neutral",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "NK-PEG40-002W-PNK-8",
    product_id: "NK-PEG40-002W",
    gtin: "194501234610",
    brand: "Nike",
    product_name: "Pegasus 40",
    category: "Running",
    subcategory: "Road Running",
    color: "Pink Foam/White",
    color_hex: "#FFB6C1",
    size: "8",
    size_type: "US",
    gender: "Women",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 53,
    condition: "new",
    material: "Engineered Mesh",
    weight_oz: 8.5,
    description: "A springy ride for every run. The women's Pegasus 40 features a narrower heel and roomier forefoot, built specifically for female runners.",
    short_description: "Women's responsive daily trainer",
    final_url: "https://nike.com/t/pegasus-40-womens-road-running/NK-PEG40-002W-PNK-8",
    image_url: "https://static.nike.com/a/images/pegasus-40-womens-pink.jpg",
    additional_images: "https://static.nike.com/a/images/pegasus-40-womens-pink-2.jpg",
    tags: "new-arrival,daily-trainer,womens",
    age_group: "adult",
    shipping_weight_lb: 1.6,
  },
  {
    sku: "NK-VFLY3-003-GRN-10",
    product_id: "NK-VFLY3-003",
    gtin: "194501234701",
    brand: "Nike",
    product_name: "Vaporfly 3",
    category: "Running",
    subcategory: "Racing",
    color: "Volt/Black",
    color_hex: "#CCFF00",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 260.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 12,
    condition: "new",
    material: "ZoomX Foam/Flyknit",
    weight_oz: 6.6,
    description: "Continue the satisfsatisfying satisfying satisfying legacy. The Nike Vaporfly 3 is our fastest road-racing shoe built for the moments when you have to have it.",
    short_description: "Elite carbon-plated marathon racer",
    final_url: "https://nike.com/t/vaporfly-3-road-racing/NK-VFLY3-003-GRN-10",
    image_url: "https://static.nike.com/a/images/vaporfly-3-volt.jpg",
    additional_images: "https://static.nike.com/a/images/vaporfly-3-volt-2.jpg,https://static.nike.com/a/images/vaporfly-3-volt-3.jpg",
    tags: "elite,carbon-plate,marathon,racing",
    age_group: "adult",
    shipping_weight_lb: 1.4,
  },

  // ============================================
  // NIKE - Basketball
  // ============================================
  {
    sku: "NK-AJ1H-010-RED-10",
    product_id: "NK-AJ1H-010",
    gtin: "194501235001",
    brand: "Nike",
    product_name: "Air Jordan 1 Retro High OG",
    category: "Basketball",
    subcategory: "Lifestyle",
    color: "Varsity Red/Black/White",
    color_hex: "#CC0000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 180.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 8,
    condition: "new",
    material: "Full-Grain Leather",
    weight_oz: 15.1,
    description: "The Air Jordan 1 Retro High remakes the iconic sneaker with premium materials and Air-Sole cushioning. A timeless design that transcends sport.",
    short_description: "Iconic basketball heritage sneaker",
    final_url: "https://nike.com/t/air-jordan-1-retro-high-og/NK-AJ1H-010-RED-10",
    image_url: "https://static.nike.com/a/images/jordan-1-chicago.jpg",
    additional_images: "https://static.nike.com/a/images/jordan-1-chicago-2.jpg",
    tags: "icon,limited,lifestyle,heritage",
    age_group: "adult",
    shipping_weight_lb: 2.4,
  },
  {
    sku: "NK-AJ1H-010-BRD-11",
    product_id: "NK-AJ1H-010",
    gtin: "194501235002",
    brand: "Nike",
    product_name: "Air Jordan 1 Retro High OG",
    category: "Basketball",
    subcategory: "Lifestyle",
    color: "Black/Varsity Red",
    color_hex: "#1A1A1A",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 180.00,
    sale_price: null,
    currency: "USD",
    in_stock: false,
    stock_qty: 0,
    condition: "new",
    material: "Full-Grain Leather",
    weight_oz: 15.5,
    description: "The Air Jordan 1 Retro High remakes the iconic sneaker with premium materials and Air-Sole cushioning. The Bred colorway honors the original 1985 release.",
    short_description: "Iconic basketball heritage sneaker",
    final_url: "https://nike.com/t/air-jordan-1-retro-high-og/NK-AJ1H-010-BRD-11",
    image_url: "https://static.nike.com/a/images/jordan-1-bred.jpg",
    additional_images: "https://static.nike.com/a/images/jordan-1-bred-2.jpg",
    tags: "icon,sold-out,lifestyle,heritage",
    age_group: "adult",
    shipping_weight_lb: 2.5,
  },
  {
    sku: "NK-LBJ21-011-PUR-12",
    product_id: "NK-LBJ21-011",
    gtin: "194501235101",
    brand: "Nike",
    product_name: "LeBron 21",
    category: "Basketball",
    subcategory: "Performance",
    color: "Court Purple/Metallic Gold",
    color_hex: "#6B3FA0",
    size: "12",
    size_type: "US",
    gender: "Men",
    price: 200.00,
    sale_price: 169.99,
    currency: "USD",
    in_stock: true,
    stock_qty: 23,
    condition: "new",
    material: "Engineered Knit/TPU",
    weight_oz: 16.3,
    description: "Built for the King's game. The LeBron 21 combines Zoom Air cushioning with a supportive midfoot cage for explosive performance on the court.",
    short_description: "LeBron's signature performance shoe",
    final_url: "https://nike.com/t/lebron-21-basketball/NK-LBJ21-011-PUR-12",
    image_url: "https://static.nike.com/a/images/lebron-21-purple.jpg",
    additional_images: "https://static.nike.com/a/images/lebron-21-purple-2.jpg",
    tags: "sale,performance,signature",
    age_group: "adult",
    shipping_weight_lb: 2.6,
  },

  // ============================================
  // NIKE - Training
  // ============================================
  {
    sku: "NK-MET9-020-BLK-10",
    product_id: "NK-MET9-020",
    gtin: "194501235201",
    brand: "Nike",
    product_name: "Metcon 9",
    category: "Training",
    subcategory: "CrossFit",
    color: "Black/Anthracite",
    color_hex: "#1C1C1C",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 150.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 38,
    condition: "new",
    material: "Mesh/Rubber",
    weight_oz: 12.8,
    description: "The Nike Metcon 9 is our most stable training shoe for your toughest workouts. A wide, flat heel and firm midsole keep you grounded during heavy lifts.",
    short_description: "Stable platform for heavy lifting",
    final_url: "https://nike.com/t/metcon-9-training/NK-MET9-020-BLK-10",
    image_url: "https://static.nike.com/a/images/metcon-9-black.jpg",
    additional_images: "https://static.nike.com/a/images/metcon-9-black-2.jpg",
    tags: "training,crossfit,weightlifting",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "NK-MET9-020W-WHT-7",
    product_id: "NK-MET9-020W",
    gtin: "194501235210",
    brand: "Nike",
    product_name: "Metcon 9",
    category: "Training",
    subcategory: "CrossFit",
    color: "White/Pink Prime",
    color_hex: "#FFFFFF",
    size: "7",
    size_type: "US",
    gender: "Women",
    price: 150.00,
    sale_price: 127.50,
    currency: "USD",
    in_stock: true,
    stock_qty: 19,
    condition: "new",
    material: "Mesh/Rubber",
    weight_oz: 10.2,
    description: "The women's Nike Metcon 9 is built specifically for your toughest workouts. A wide, flat heel provides stability during heavy lifts.",
    short_description: "Women's stable training platform",
    final_url: "https://nike.com/t/metcon-9-womens-training/NK-MET9-020W-WHT-7",
    image_url: "https://static.nike.com/a/images/metcon-9-womens-white.jpg",
    additional_images: "https://static.nike.com/a/images/metcon-9-womens-white-2.jpg",
    tags: "sale,training,crossfit,womens",
    age_group: "adult",
    shipping_weight_lb: 1.7,
  },

  // ============================================
  // ADIDAS - Running
  // ============================================
  {
    sku: "AD-UB23-001-BLK-10",
    product_id: "AD-UB23-001",
    gtin: "195501234001",
    brand: "Adidas",
    product_name: "Ultraboost 23",
    category: "Running",
    subcategory: "Road Running",
    color: "Core Black/Cloud White",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 190.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 56,
    condition: "new",
    material: "Primeknit+/Boost",
    weight_oz: 11.2,
    description: "Experience epic energy with every stride. The Ultraboost 23 features a Linear Energy Push system and Boost midsole for incredible responsiveness.",
    short_description: "Maximum energy return with Boost",
    final_url: "https://adidas.com/us/ultraboost-23/AD-UB23-001-BLK-10",
    image_url: "https://assets.adidas.com/images/ultraboost-23-black.jpg",
    additional_images: "https://assets.adidas.com/images/ultraboost-23-black-2.jpg,https://assets.adidas.com/images/ultraboost-23-black-3.jpg",
    tags: "bestseller,boost,premium",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "AD-UB23-001-WHT-10",
    product_id: "AD-UB23-001",
    gtin: "195501234002",
    brand: "Adidas",
    product_name: "Ultraboost 23",
    category: "Running",
    subcategory: "Road Running",
    color: "Cloud White/Core Black",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 190.00,
    sale_price: 152.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 34,
    condition: "new",
    material: "Primeknit+/Boost",
    weight_oz: 11.2,
    description: "Experience epic energy with every stride. The Ultraboost 23 features a Linear Energy Push system and Boost midsole for incredible responsiveness.",
    short_description: "Maximum energy return with Boost",
    final_url: "https://adidas.com/us/ultraboost-23/AD-UB23-001-WHT-10",
    image_url: "https://assets.adidas.com/images/ultraboost-23-white.jpg",
    additional_images: "https://assets.adidas.com/images/ultraboost-23-white-2.jpg",
    tags: "sale,boost,premium",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "AD-UB23-001W-PNK-8",
    product_id: "AD-UB23-001W",
    gtin: "195501234010",
    brand: "Adidas",
    product_name: "Ultraboost 23",
    category: "Running",
    subcategory: "Road Running",
    color: "Beam Pink/Cloud White",
    color_hex: "#FF69B4",
    size: "8",
    size_type: "US",
    gender: "Women",
    price: 190.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 42,
    condition: "new",
    material: "Primeknit+/Boost",
    weight_oz: 9.1,
    description: "Experience epic energy with every stride. The women's Ultraboost 23 features a female-specific fit with Boost midsole cushioning.",
    short_description: "Women's maximum energy return",
    final_url: "https://adidas.com/us/ultraboost-23-womens/AD-UB23-001W-PNK-8",
    image_url: "https://assets.adidas.com/images/ultraboost-23-womens-pink.jpg",
    additional_images: "https://assets.adidas.com/images/ultraboost-23-womens-pink-2.jpg",
    tags: "new-arrival,boost,womens",
    age_group: "adult",
    shipping_weight_lb: 1.6,
  },
  {
    sku: "AD-ADPRO-002-ORG-9",
    product_id: "AD-ADPRO-002",
    gtin: "195501234101",
    brand: "Adidas",
    product_name: "Adizero Adios Pro 3",
    category: "Running",
    subcategory: "Racing",
    color: "Solar Orange/Core Black",
    color_hex: "#FF6600",
    size: "9",
    size_type: "US",
    gender: "Unisex",
    price: 250.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 15,
    condition: "new",
    material: "Lightstrike Pro/EnergyRods",
    weight_oz: 7.1,
    description: "The Adizero Adios Pro 3 is built for record-breaking speed. ENERGYRODS 2.0 and LIGHTSTRIKE PRO foam deliver explosive propulsion.",
    short_description: "World-record breaking marathon racer",
    final_url: "https://adidas.com/us/adizero-adios-pro-3/AD-ADPRO-002-ORG-9",
    image_url: "https://assets.adidas.com/images/adios-pro-3-orange.jpg",
    additional_images: "https://assets.adidas.com/images/adios-pro-3-orange-2.jpg",
    tags: "elite,carbon-plate,marathon,racing",
    age_group: "adult",
    shipping_weight_lb: 1.5,
  },

  // ============================================
  // ADIDAS - Lifestyle
  // ============================================
  {
    sku: "AD-SAMBA-010-BLK-10",
    product_id: "AD-SAMBA-010",
    gtin: "195501235001",
    brand: "Adidas",
    product_name: "Samba OG",
    category: "Lifestyle",
    subcategory: "Originals",
    color: "Core Black/Cloud White/Gum",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 100.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 89,
    condition: "new",
    material: "Full-Grain Leather",
    weight_oz: 12.5,
    description: "Born on the pitch, the Samba has become a street-style icon. This OG version features premium leather and the iconic gum sole.",
    short_description: "Iconic terrace style since 1950",
    final_url: "https://adidas.com/us/samba-og/AD-SAMBA-010-BLK-10",
    image_url: "https://assets.adidas.com/images/samba-og-black.jpg",
    additional_images: "https://assets.adidas.com/images/samba-og-black-2.jpg,https://assets.adidas.com/images/samba-og-black-3.jpg",
    tags: "icon,heritage,trending",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "AD-SAMBA-010-WHT-9",
    product_id: "AD-SAMBA-010",
    gtin: "195501235002",
    brand: "Adidas",
    product_name: "Samba OG",
    category: "Lifestyle",
    subcategory: "Originals",
    color: "Cloud White/Core Black/Gum",
    color_hex: "#FFFFFF",
    size: "9",
    size_type: "US",
    gender: "Unisex",
    price: 100.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 67,
    condition: "new",
    material: "Full-Grain Leather",
    weight_oz: 12.2,
    description: "Born on the pitch, the Samba has become a street-style icon. This OG version features premium leather and the iconic gum sole.",
    short_description: "Iconic terrace style since 1950",
    final_url: "https://adidas.com/us/samba-og/AD-SAMBA-010-WHT-9",
    image_url: "https://assets.adidas.com/images/samba-og-white.jpg",
    additional_images: "https://assets.adidas.com/images/samba-og-white-2.jpg",
    tags: "icon,heritage,trending",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "AD-GAZL-011-NVY-10",
    product_id: "AD-GAZL-011",
    gtin: "195501235101",
    brand: "Adidas",
    product_name: "Gazelle",
    category: "Lifestyle",
    subcategory: "Originals",
    color: "Collegiate Navy/Cloud White",
    color_hex: "#1E3A5F",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 100.00,
    sale_price: 80.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 45,
    condition: "new",
    material: "Suede/Leather",
    weight_oz: 11.8,
    description: "The Gazelle keeps its classic suede look while adding modern comfort. A true icon of adidas Originals style.",
    short_description: "70s suede icon, modern comfort",
    final_url: "https://adidas.com/us/gazelle/AD-GAZL-011-NVY-10",
    image_url: "https://assets.adidas.com/images/gazelle-navy.jpg",
    additional_images: "https://assets.adidas.com/images/gazelle-navy-2.jpg",
    tags: "sale,heritage,retro",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "AD-STNSM-012-WHT-10",
    product_id: "AD-STNSM-012",
    gtin: "195501235201",
    brand: "Adidas",
    product_name: "Stan Smith",
    category: "Lifestyle",
    subcategory: "Originals",
    color: "Cloud White/Green",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 95.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 112,
    condition: "new",
    material: "Full-Grain Leather",
    weight_oz: 11.5,
    description: "Clean, classic, iconic. The Stan Smith has been a wardrobe staple since 1971. Premium leather and the signature green heel tab complete the look.",
    short_description: "The original clean white sneaker",
    final_url: "https://adidas.com/us/stan-smith/AD-STNSM-012-WHT-10",
    image_url: "https://assets.adidas.com/images/stan-smith-white-green.jpg",
    additional_images: "https://assets.adidas.com/images/stan-smith-white-green-2.jpg",
    tags: "icon,classic,wardrobe-essential",
    age_group: "adult",
    shipping_weight_lb: 1.8,
  },

  // ============================================
  // NEW BALANCE - Running
  // ============================================
  {
    sku: "NB-1080V14-001-BLK-10",
    product_id: "NB-1080V14-001",
    gtin: "196501234001",
    brand: "New Balance",
    product_name: "Fresh Foam X 1080v14",
    category: "Running",
    subcategory: "Road Running",
    color: "Black/Gum",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 165.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 48,
    condition: "new",
    material: "Hypoknit/Fresh Foam X",
    weight_oz: 10.1,
    description: "The Fresh Foam X 1080v14 delivers premium cushioning for everyday runs. Hypoknit upper provides stretch and support where you need it most.",
    short_description: "Premium cushioned daily trainer",
    final_url: "https://newbalance.com/pd/fresh-foam-1080v14/NB-1080V14-001-BLK-10",
    image_url: "https://nb.scene7.com/is/image/NB/1080v14-black",
    additional_images: "https://nb.scene7.com/is/image/NB/1080v14-black-2",
    tags: "premium,cushioned,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "NB-1080V14-001-BLU-11",
    product_id: "NB-1080V14-001",
    gtin: "196501234002",
    brand: "New Balance",
    product_name: "Fresh Foam X 1080v14",
    category: "Running",
    subcategory: "Road Running",
    color: "Heritage Blue/Bright Lapis",
    color_hex: "#3366CC",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 165.00,
    sale_price: 140.25,
    currency: "USD",
    in_stock: true,
    stock_qty: 31,
    condition: "new",
    material: "Hypoknit/Fresh Foam X",
    weight_oz: 10.4,
    description: "The Fresh Foam X 1080v14 delivers premium cushioning for everyday runs. Hypoknit upper provides stretch and support where you need it most.",
    short_description: "Premium cushioned daily trainer",
    final_url: "https://newbalance.com/pd/fresh-foam-1080v14/NB-1080V14-001-BLU-11",
    image_url: "https://nb.scene7.com/is/image/NB/1080v14-blue",
    additional_images: "https://nb.scene7.com/is/image/NB/1080v14-blue-2",
    tags: "sale,cushioned,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "NB-REBEL4-002-YEL-9",
    product_id: "NB-REBEL4-002",
    gtin: "196501234101",
    brand: "New Balance",
    product_name: "FuelCell Rebel v4",
    category: "Running",
    subcategory: "Road Running",
    color: "Thirty Watt/Blue Oasis",
    color_hex: "#FFD700",
    size: "9",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 62,
    condition: "new",
    material: "Knit/FuelCell Foam",
    weight_oz: 8.1,
    description: "The FuelCell Rebel v4 combines lightweight speed with energetic cushioning. The propulsive FuelCell foam makes every run feel fast.",
    short_description: "Lightweight and fast daily trainer",
    final_url: "https://newbalance.com/pd/fuelcell-rebel-v4/NB-REBEL4-002-YEL-9",
    image_url: "https://nb.scene7.com/is/image/NB/rebel-v4-yellow",
    additional_images: "https://nb.scene7.com/is/image/NB/rebel-v4-yellow-2",
    tags: "new-arrival,fast,lightweight",
    age_group: "adult",
    shipping_weight_lb: 1.6,
  },
  {
    sku: "NB-SCEL3-003-WHT-10",
    product_id: "NB-SCEL3-003",
    gtin: "196501234201",
    brand: "New Balance",
    product_name: "FuelCell SuperComp Elite v4",
    category: "Running",
    subcategory: "Racing",
    color: "White/Bleached Lime Glo",
    color_hex: "#F5F5F5",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 275.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 9,
    condition: "new",
    material: "FuelCell Elite/Energy Arc",
    weight_oz: 6.9,
    description: "Engineered for elite racers. The SuperComp Elite v4 features Energy Arc carbon plate technology for maximum propulsion.",
    short_description: "Carbon-plated elite marathon racer",
    final_url: "https://newbalance.com/pd/fuelcell-supercomp-elite-v4/NB-SCEL3-003-WHT-10",
    image_url: "https://nb.scene7.com/is/image/NB/supercomp-elite-v4-white",
    additional_images: "https://nb.scene7.com/is/image/NB/supercomp-elite-v4-white-2",
    tags: "elite,carbon-plate,marathon,racing",
    age_group: "adult",
    shipping_weight_lb: 1.4,
  },

  // ============================================
  // NEW BALANCE - Lifestyle
  // ============================================
  {
    sku: "NB-550-010-WHT-10",
    product_id: "NB-550-010",
    gtin: "196501235001",
    brand: "New Balance",
    product_name: "550",
    category: "Lifestyle",
    subcategory: "Heritage",
    color: "White/Green",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 130.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 34,
    condition: "new",
    material: "Leather/Synthetic",
    weight_oz: 14.2,
    description: "Originally designed for basketball in 1989, the 550 has evolved into a streetwear icon. Premium leather and retro styling define this classic.",
    short_description: "80s basketball icon, modern essential",
    final_url: "https://newbalance.com/pd/550/NB-550-010-WHT-10",
    image_url: "https://nb.scene7.com/is/image/NB/550-white-green",
    additional_images: "https://nb.scene7.com/is/image/NB/550-white-green-2",
    tags: "trending,heritage,streetwear",
    age_group: "adult",
    shipping_weight_lb: 2.2,
  },
  {
    sku: "NB-550-010-BLU-9",
    product_id: "NB-550-010",
    gtin: "196501235002",
    brand: "New Balance",
    product_name: "550",
    category: "Lifestyle",
    subcategory: "Heritage",
    color: "White/Navy",
    color_hex: "#FFFFFF",
    size: "9",
    size_type: "US",
    gender: "Unisex",
    price: 130.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 28,
    condition: "new",
    material: "Leather/Synthetic",
    weight_oz: 13.9,
    description: "Originally designed for basketball in 1989, the 550 has evolved into a streetwear icon. Premium leather and retro styling define this classic.",
    short_description: "80s basketball icon, modern essential",
    final_url: "https://newbalance.com/pd/550/NB-550-010-BLU-9",
    image_url: "https://nb.scene7.com/is/image/NB/550-white-navy",
    additional_images: "https://nb.scene7.com/is/image/NB/550-white-navy-2",
    tags: "trending,heritage,streetwear",
    age_group: "adult",
    shipping_weight_lb: 2.1,
  },
  {
    sku: "NB-2002R-011-GRY-10",
    product_id: "NB-2002R-011",
    gtin: "196501235101",
    brand: "New Balance",
    product_name: "2002R",
    category: "Lifestyle",
    subcategory: "Heritage",
    color: "Rain Cloud/Phantom",
    color_hex: "#A8A8A8",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 150.00,
    sale_price: 127.50,
    currency: "USD",
    in_stock: true,
    stock_qty: 41,
    condition: "new",
    material: "Suede/Mesh",
    weight_oz: 12.6,
    description: "The 2002R brings Y2K style into the present. Premium suede and mesh upper sits atop responsive N-ERGY cushioning.",
    short_description: "Y2K runner with premium materials",
    final_url: "https://newbalance.com/pd/2002r/NB-2002R-011-GRY-10",
    image_url: "https://nb.scene7.com/is/image/NB/2002r-grey",
    additional_images: "https://nb.scene7.com/is/image/NB/2002r-grey-2",
    tags: "sale,retro,premium",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },

  // ============================================
  // HOKA - Running
  // ============================================
  {
    sku: "HK-CLIF9-001-BLK-10",
    product_id: "HK-CLIF9-001",
    gtin: "197501234001",
    brand: "Hoka",
    product_name: "Clifton 9",
    category: "Running",
    subcategory: "Road Running",
    color: "Black/White",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 145.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 73,
    condition: "new",
    material: "Engineered Mesh/EVA",
    weight_oz: 9.0,
    description: "Lighter than ever while still delivering the signature HOKA cushion. The Clifton 9 features a new softer foam for an ultra-smooth ride.",
    short_description: "Lighter, softer, signature HOKA feel",
    final_url: "https://hoka.com/en/us/clifton-9/HK-CLIF9-001-BLK-10",
    image_url: "https://hoka.com/media/clifton-9-black.jpg",
    additional_images: "https://hoka.com/media/clifton-9-black-2.jpg,https://hoka.com/media/clifton-9-black-3.jpg",
    tags: "bestseller,cushioned,lightweight",
    age_group: "adult",
    shipping_weight_lb: 1.7,
  },
  {
    sku: "HK-CLIF9-001-BLU-11",
    product_id: "HK-CLIF9-001",
    gtin: "197501234002",
    brand: "Hoka",
    product_name: "Clifton 9",
    category: "Running",
    subcategory: "Road Running",
    color: "Virtual Blue/Cerise",
    color_hex: "#4169E1",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 145.00,
    sale_price: 123.25,
    currency: "USD",
    in_stock: true,
    stock_qty: 45,
    condition: "new",
    material: "Engineered Mesh/EVA",
    weight_oz: 9.3,
    description: "Lighter than ever while still delivering the signature HOKA cushion. The Clifton 9 features a new softer foam for an ultra-smooth ride.",
    short_description: "Lighter, softer, signature HOKA feel",
    final_url: "https://hoka.com/en/us/clifton-9/HK-CLIF9-001-BLU-11",
    image_url: "https://hoka.com/media/clifton-9-blue.jpg",
    additional_images: "https://hoka.com/media/clifton-9-blue-2.jpg",
    tags: "sale,cushioned,lightweight",
    age_group: "adult",
    shipping_weight_lb: 1.8,
  },
  {
    sku: "HK-CLIF9-001W-LVN-8",
    product_id: "HK-CLIF9-001W",
    gtin: "197501234010",
    brand: "Hoka",
    product_name: "Clifton 9",
    category: "Running",
    subcategory: "Road Running",
    color: "Lavender/Ether",
    color_hex: "#E6E6FA",
    size: "8",
    size_type: "US",
    gender: "Women",
    price: 145.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 58,
    condition: "new",
    material: "Engineered Mesh/EVA",
    weight_oz: 7.2,
    description: "The women's Clifton 9 delivers signature HOKA cushion in a lighter package. Perfect for everyday runs and all-day comfort.",
    short_description: "Women's lightweight cushioned trainer",
    final_url: "https://hoka.com/en/us/clifton-9-womens/HK-CLIF9-001W-LVN-8",
    image_url: "https://hoka.com/media/clifton-9-womens-lavender.jpg",
    additional_images: "https://hoka.com/media/clifton-9-womens-lavender-2.jpg",
    tags: "bestseller,cushioned,womens",
    age_group: "adult",
    shipping_weight_lb: 1.4,
  },
  {
    sku: "HK-BNDI8-002-WHT-10",
    product_id: "HK-BNDI8-002",
    gtin: "197501234101",
    brand: "Hoka",
    product_name: "Bondi 8",
    category: "Running",
    subcategory: "Road Running",
    color: "White/White",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 165.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 52,
    condition: "new",
    material: "Engineered Mesh/EVA",
    weight_oz: 10.8,
    description: "Maximum cushion for the long haul. The Bondi 8 features our softest foam yet and a new extended heel geometry for smooth landings.",
    short_description: "Maximum cushion, ultra-soft ride",
    final_url: "https://hoka.com/en/us/bondi-8/HK-BNDI8-002-WHT-10",
    image_url: "https://hoka.com/media/bondi-8-white.jpg",
    additional_images: "https://hoka.com/media/bondi-8-white-2.jpg",
    tags: "max-cushion,recovery,comfort",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "HK-SPDG5-003-ORG-10",
    product_id: "HK-SPDG5-003",
    gtin: "197501234201",
    brand: "Hoka",
    product_name: "Speedgoat 5",
    category: "Running",
    subcategory: "Trail Running",
    color: "Thyme/Radiant Yellow",
    color_hex: "#FF8C00",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 155.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 37,
    condition: "new",
    material: "Mesh/Vibram Megagrip",
    weight_oz: 10.6,
    description: "Conquer any trail with confidence. The Speedgoat 5 features Vibram Megagrip outsole and signature HOKA cushioning for technical terrain.",
    short_description: "Cushioned trail beast with Vibram grip",
    final_url: "https://hoka.com/en/us/speedgoat-5/HK-SPDG5-003-ORG-10",
    image_url: "https://hoka.com/media/speedgoat-5-orange.jpg",
    additional_images: "https://hoka.com/media/speedgoat-5-orange-2.jpg",
    tags: "trail,vibram,all-terrain",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },

  // ============================================
  // ON - Running
  // ============================================
  {
    sku: "ON-CLMST-001-BLK-10",
    product_id: "ON-CLMST-001",
    gtin: "198501234001",
    brand: "On",
    product_name: "Cloudmonster",
    category: "Running",
    subcategory: "Road Running",
    color: "All Black",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 170.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 41,
    condition: "new",
    material: "Engineered Mesh/CloudTec",
    weight_oz: 10.6,
    description: "Maximum cushioning meets explosive energy return. The Cloudmonster features our biggest CloudTec elements for a massive soft landing and powerful takeoff.",
    short_description: "Max cushion with CloudTec technology",
    final_url: "https://on.com/en-us/cloudmonster/ON-CLMST-001-BLK-10",
    image_url: "https://on.com/media/cloudmonster-black.jpg",
    additional_images: "https://on.com/media/cloudmonster-black-2.jpg,https://on.com/media/cloudmonster-black-3.jpg",
    tags: "max-cushion,cloudtec,swiss-engineering",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "ON-CLMST-001-WHT-10",
    product_id: "ON-CLMST-001",
    gtin: "198501234002",
    brand: "On",
    product_name: "Cloudmonster",
    category: "Running",
    subcategory: "Road Running",
    color: "Undyed White/Flame",
    color_hex: "#F5F5F0",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 170.00,
    sale_price: 144.50,
    currency: "USD",
    in_stock: true,
    stock_qty: 29,
    condition: "new",
    material: "Engineered Mesh/CloudTec",
    weight_oz: 10.6,
    description: "Maximum cushioning meets explosive energy return. The Cloudmonster features our biggest CloudTec elements for a massive soft landing and powerful takeoff.",
    short_description: "Max cushion with CloudTec technology",
    final_url: "https://on.com/en-us/cloudmonster/ON-CLMST-001-WHT-10",
    image_url: "https://on.com/media/cloudmonster-white.jpg",
    additional_images: "https://on.com/media/cloudmonster-white-2.jpg",
    tags: "sale,cloudtec,swiss-engineering",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "ON-CLD5-002-BLK-9",
    product_id: "ON-CLD5-002",
    gtin: "198501234101",
    brand: "On",
    product_name: "Cloud 5",
    category: "Running",
    subcategory: "Road Running",
    color: "All Black",
    color_hex: "#000000",
    size: "9",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 86,
    condition: "new",
    material: "Engineered Mesh/CloudTec",
    weight_oz: 8.5,
    description: "The iconic everyday trainer. Cloud 5 brings the signature CloudTec sensation to all-day wear with a seamless speed-lacing system.",
    short_description: "Everyday comfort with Swiss design",
    final_url: "https://on.com/en-us/cloud-5/ON-CLD5-002-BLK-9",
    image_url: "https://on.com/media/cloud-5-black.jpg",
    additional_images: "https://on.com/media/cloud-5-black-2.jpg",
    tags: "bestseller,everyday,travel",
    age_group: "adult",
    shipping_weight_lb: 1.6,
  },
  {
    sku: "ON-CLSRF-003-NVY-10",
    product_id: "ON-CLSRF-003",
    gtin: "198501234201",
    brand: "On",
    product_name: "Cloudsurfer",
    category: "Running",
    subcategory: "Road Running",
    color: "Midnight/Cobalt",
    color_hex: "#191970",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 33,
    condition: "new",
    material: "Engineered Mesh/Helion HF",
    weight_oz: 9.5,
    description: "Next-gen performance running. The Cloudsurfer features Helion HF foam and CloudTec Phase technology for a responsive, smooth ride.",
    short_description: "Performance trainer with Helion foam",
    final_url: "https://on.com/en-us/cloudsurfer/ON-CLSRF-003-NVY-10",
    image_url: "https://on.com/media/cloudsurfer-navy.jpg",
    additional_images: "https://on.com/media/cloudsurfer-navy-2.jpg",
    tags: "performance,helion,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 1.8,
  },

  // ============================================
  // ASICS - Running
  // ============================================
  {
    sku: "AS-KAY30-001-BLK-10",
    product_id: "AS-KAY30-001",
    gtin: "199501234001",
    brand: "ASICS",
    product_name: "Gel-Kayano 30",
    category: "Running",
    subcategory: "Stability",
    color: "Black/Sheet Rock",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 54,
    condition: "new",
    material: "Engineered Mesh/FF Blast+",
    weight_oz: 11.1,
    description: "30 years of legendary stability. The Gel-Kayano 30 combines 4D GUIDANCE SYSTEM technology with FF BLAST PLUS cushioning for adaptive support.",
    short_description: "Legendary stability, 30th anniversary",
    final_url: "https://asics.com/us/en-us/gel-kayano-30/AS-KAY30-001-BLK-10",
    image_url: "https://asics.com/media/gel-kayano-30-black.jpg",
    additional_images: "https://asics.com/media/gel-kayano-30-black-2.jpg",
    tags: "stability,support,anniversary",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "AS-KAY30-001-BLU-11",
    product_id: "AS-KAY30-001",
    gtin: "199501234002",
    brand: "ASICS",
    product_name: "Gel-Kayano 30",
    category: "Running",
    subcategory: "Stability",
    color: "Illusion Blue/Glow Yellow",
    color_hex: "#0066CC",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: 136.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 38,
    condition: "new",
    material: "Engineered Mesh/FF Blast+",
    weight_oz: 11.4,
    description: "30 years of legendary stability. The Gel-Kayano 30 combines 4D GUIDANCE SYSTEM technology with FF BLAST PLUS cushioning for adaptive support.",
    short_description: "Legendary stability, 30th anniversary",
    final_url: "https://asics.com/us/en-us/gel-kayano-30/AS-KAY30-001-BLU-11",
    image_url: "https://asics.com/media/gel-kayano-30-blue.jpg",
    additional_images: "https://asics.com/media/gel-kayano-30-blue-2.jpg",
    tags: "sale,stability,support",
    age_group: "adult",
    shipping_weight_lb: 2.1,
  },
  {
    sku: "AS-NIMB25-002-GRY-10",
    product_id: "AS-NIMB25-002",
    gtin: "199501234101",
    brand: "ASICS",
    product_name: "Gel-Nimbus 25",
    category: "Running",
    subcategory: "Neutral",
    color: "Sheet Rock/Hazard Green",
    color_hex: "#808080",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 47,
    condition: "new",
    material: "Engineered Mesh/FF Blast+",
    weight_oz: 10.6,
    description: "Cloud-like cushioning for long runs. The Gel-Nimbus 25 features FF BLAST PLUS ECO cushioning and PureGEL technology for supreme comfort.",
    short_description: "Maximum cushion neutral trainer",
    final_url: "https://asics.com/us/en-us/gel-nimbus-25/AS-NIMB25-002-GRY-10",
    image_url: "https://asics.com/media/gel-nimbus-25-grey.jpg",
    additional_images: "https://asics.com/media/gel-nimbus-25-grey-2.jpg",
    tags: "cushioned,neutral,long-distance",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "AS-NOVA4-003-BLU-10",
    product_id: "AS-NOVA4-003",
    gtin: "199501234201",
    brand: "ASICS",
    product_name: "Novablast 4",
    category: "Running",
    subcategory: "Neutral",
    color: "Waterscape/Illuminating Green",
    color_hex: "#00CED1",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 61,
    condition: "new",
    material: "Engineered Mesh/FF Blast+",
    weight_oz: 9.3,
    description: "Bouncy fun for every run. The Novablast 4 delivers trampoline-like energy return with FF BLAST PLUS foam and a playful personality.",
    short_description: "Bouncy, energetic daily trainer",
    final_url: "https://asics.com/us/en-us/novablast-4/AS-NOVA4-003-BLU-10",
    image_url: "https://asics.com/media/novablast-4-blue.jpg",
    additional_images: "https://asics.com/media/novablast-4-blue-2.jpg",
    tags: "bouncy,fun,energetic",
    age_group: "adult",
    shipping_weight_lb: 1.8,
  },
  {
    sku: "AS-MSKY+-004-WHT-9",
    product_id: "AS-MSKY+-004",
    gtin: "199501234301",
    brand: "ASICS",
    product_name: "Metaspeed Sky+",
    category: "Running",
    subcategory: "Racing",
    color: "White/Sunrise Red",
    color_hex: "#FFFFFF",
    size: "9",
    size_type: "US",
    gender: "Unisex",
    price: 250.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 11,
    condition: "new",
    material: "Motion Wrap/FF Turbo+",
    weight_oz: 6.7,
    description: "Built for stride runners. The Metaspeed Sky+ combines a full-length carbon plate with FF TURBO PLUS foam for explosive marathon speed.",
    short_description: "Carbon-plated elite marathon racer",
    final_url: "https://asics.com/us/en-us/metaspeed-sky-plus/AS-MSKY+-004-WHT-9",
    image_url: "https://asics.com/media/metaspeed-sky-plus-white.jpg",
    additional_images: "https://asics.com/media/metaspeed-sky-plus-white-2.jpg",
    tags: "elite,carbon-plate,marathon,racing",
    age_group: "adult",
    shipping_weight_lb: 1.4,
  },

  // ============================================
  // BROOKS - Running
  // ============================================
  {
    sku: "BR-GHST15-001-BLK-10",
    product_id: "BR-GHST15-001",
    gtin: "200501234001",
    brand: "Brooks",
    product_name: "Ghost 15",
    category: "Running",
    subcategory: "Neutral",
    color: "Black/Ebony/Primer",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 78,
    condition: "new",
    material: "Engineered Mesh/DNA LOFT",
    weight_oz: 10.1,
    description: "Your go-to for every run. The Ghost 15 delivers smooth transitions and soft cushioning with DNA LOFT foam and a segmented crash pad.",
    short_description: "Smooth, cushioned neutral trainer",
    final_url: "https://brooks.com/en_us/ghost-15-mens/BR-GHST15-001-BLK-10",
    image_url: "https://brooks.com/media/ghost-15-black.jpg",
    additional_images: "https://brooks.com/media/ghost-15-black-2.jpg",
    tags: "bestseller,neutral,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "BR-GHST15-001-BLU-11",
    product_id: "BR-GHST15-001",
    gtin: "200501234002",
    brand: "Brooks",
    product_name: "Ghost 15",
    category: "Running",
    subcategory: "Neutral",
    color: "Blue/Nightlife/White",
    color_hex: "#4169E1",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: 119.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 52,
    condition: "new",
    material: "Engineered Mesh/DNA LOFT",
    weight_oz: 10.4,
    description: "Your go-to for every run. The Ghost 15 delivers smooth transitions and soft cushioning with DNA LOFT foam and a segmented crash pad.",
    short_description: "Smooth, cushioned neutral trainer",
    final_url: "https://brooks.com/en_us/ghost-15-mens/BR-GHST15-001-BLU-11",
    image_url: "https://brooks.com/media/ghost-15-blue.jpg",
    additional_images: "https://brooks.com/media/ghost-15-blue-2.jpg",
    tags: "sale,neutral,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "BR-GLYC20-002-WHT-10",
    product_id: "BR-GLYC20-002",
    gtin: "200501234101",
    brand: "Brooks",
    product_name: "Glycerin 20",
    category: "Running",
    subcategory: "Neutral",
    color: "White/Alloy/Red",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 43,
    condition: "new",
    material: "Engineered Mesh/DNA LOFT v3",
    weight_oz: 10.6,
    description: "Premium cushioning for every stride. The Glycerin 20 features our softest DNA LOFT v3 foam and a nitrogen-infused midsole for cloud-like comfort.",
    short_description: "Premium soft cushioned trainer",
    final_url: "https://brooks.com/en_us/glycerin-20-mens/BR-GLYC20-002-WHT-10",
    image_url: "https://brooks.com/media/glycerin-20-white.jpg",
    additional_images: "https://brooks.com/media/glycerin-20-white-2.jpg",
    tags: "premium,cushioned,soft",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },
  {
    sku: "BR-ADGTS23-003-BLK-10",
    product_id: "BR-ADGTS23-003",
    gtin: "200501234201",
    brand: "Brooks",
    product_name: "Adrenaline GTS 23",
    category: "Running",
    subcategory: "Stability",
    color: "Black/Black/Ebony",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 65,
    condition: "new",
    material: "Engineered Mesh/DNA LOFT",
    weight_oz: 10.6,
    description: "Trusted support for overpronators. The Adrenaline GTS 23 features GuideRails holistic support system and DNA LOFT cushioning.",
    short_description: "Holistic support with GuideRails",
    final_url: "https://brooks.com/en_us/adrenaline-gts-23-mens/BR-ADGTS23-003-BLK-10",
    image_url: "https://brooks.com/media/adrenaline-gts-23-black.jpg",
    additional_images: "https://brooks.com/media/adrenaline-gts-23-black-2.jpg",
    tags: "stability,support,guiderails",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },

  // ============================================
  // SAUCONY - Running
  // ============================================
  {
    sku: "SC-ENDSPD3-001-WHT-10",
    product_id: "SC-ENDSPD3-001",
    gtin: "201501234001",
    brand: "Saucony",
    product_name: "Endorphin Speed 3",
    category: "Running",
    subcategory: "Racing",
    color: "White/Vizired",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 170.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 44,
    condition: "new",
    material: "Engineered Mesh/PWRRUN PB",
    weight_oz: 7.8,
    description: "Speedroll technology and a nylon plate make every run feel fast. The Endorphin Speed 3 is the versatile speed shoe for training and racing.",
    short_description: "Versatile speed trainer with plate",
    final_url: "https://saucony.com/en/endorphin-speed-3/SC-ENDSPD3-001-WHT-10",
    image_url: "https://saucony.com/media/endorphin-speed-3-white.jpg",
    additional_images: "https://saucony.com/media/endorphin-speed-3-white-2.jpg",
    tags: "speed,plate,versatile",
    age_group: "adult",
    shipping_weight_lb: 1.6,
  },
  {
    sku: "SC-ENDSPD3-001-BLK-11",
    product_id: "SC-ENDSPD3-001",
    gtin: "201501234002",
    brand: "Saucony",
    product_name: "Endorphin Speed 3",
    category: "Running",
    subcategory: "Racing",
    color: "Black/Goldstruck",
    color_hex: "#000000",
    size: "11",
    size_type: "US",
    gender: "Men",
    price: 170.00,
    sale_price: 144.50,
    currency: "USD",
    in_stock: true,
    stock_qty: 31,
    condition: "new",
    material: "Engineered Mesh/PWRRUN PB",
    weight_oz: 8.0,
    description: "Speedroll technology and a nylon plate make every run feel fast. The Endorphin Speed 3 is the versatile speed shoe for training and racing.",
    short_description: "Versatile speed trainer with plate",
    final_url: "https://saucony.com/en/endorphin-speed-3/SC-ENDSPD3-001-BLK-11",
    image_url: "https://saucony.com/media/endorphin-speed-3-black.jpg",
    additional_images: "https://saucony.com/media/endorphin-speed-3-black-2.jpg",
    tags: "sale,speed,plate",
    age_group: "adult",
    shipping_weight_lb: 1.7,
  },
  {
    sku: "SC-ENDPRO3-002-RED-9",
    product_id: "SC-ENDPRO3-002",
    gtin: "201501234101",
    brand: "Saucony",
    product_name: "Endorphin Pro 3",
    category: "Running",
    subcategory: "Racing",
    color: "Red/Vizired",
    color_hex: "#FF0000",
    size: "9",
    size_type: "US",
    gender: "Unisex",
    price: 225.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 14,
    condition: "new",
    material: "Engineered Mesh/PWRRUN PB",
    weight_oz: 6.6,
    description: "Race day domination. The Endorphin Pro 3 combines a full-length carbon plate with PWRRUN PB foam for maximum propulsion.",
    short_description: "Carbon-plated elite racer",
    final_url: "https://saucony.com/en/endorphin-pro-3/SC-ENDPRO3-002-RED-9",
    image_url: "https://saucony.com/media/endorphin-pro-3-red.jpg",
    additional_images: "https://saucony.com/media/endorphin-pro-3-red-2.jpg",
    tags: "elite,carbon-plate,marathon,racing",
    age_group: "adult",
    shipping_weight_lb: 1.4,
  },
  {
    sku: "SC-TRMPH21-003-GRY-10",
    product_id: "SC-TRMPH21-003",
    gtin: "201501234201",
    brand: "Saucony",
    product_name: "Triumph 21",
    category: "Running",
    subcategory: "Neutral",
    color: "Fog/Vapor",
    color_hex: "#A8A8A8",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 48,
    condition: "new",
    material: "Engineered Mesh/PWRRUN+",
    weight_oz: 10.1,
    description: "Plush cushioning for long-distance comfort. The Triumph 21 features PWRRUN+ foam and a new FORMFIT design for an adaptive fit.",
    short_description: "Maximum cushioned daily trainer",
    final_url: "https://saucony.com/en/triumph-21/SC-TRMPH21-003-GRY-10",
    image_url: "https://saucony.com/media/triumph-21-grey.jpg",
    additional_images: "https://saucony.com/media/triumph-21-grey-2.jpg",
    tags: "cushioned,comfort,neutral",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },

  // ============================================
  // PUMA - Running
  // ============================================
  {
    sku: "PM-DEVN2-001-BLK-10",
    product_id: "PM-DEVN2-001",
    gtin: "202501234001",
    brand: "Puma",
    product_name: "Deviate Nitro 2",
    category: "Running",
    subcategory: "Racing",
    color: "Puma Black/Lime Squeeze",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 180.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 36,
    condition: "new",
    material: "Engineered Mesh/NITRO Foam",
    weight_oz: 8.6,
    description: "Explosive speed with NITRO foam and a carbon plate. The Deviate Nitro 2 delivers race-day performance for tempo runs and competition.",
    short_description: "Carbon-plated racer with NITRO foam",
    final_url: "https://puma.com/us/en/deviate-nitro-2/PM-DEVN2-001-BLK-10",
    image_url: "https://puma.com/media/deviate-nitro-2-black.jpg",
    additional_images: "https://puma.com/media/deviate-nitro-2-black-2.jpg",
    tags: "carbon-plate,nitro,racing",
    age_group: "adult",
    shipping_weight_lb: 1.7,
  },
  {
    sku: "PM-VELN2-002-BLU-10",
    product_id: "PM-VELN2-002",
    gtin: "202501234101",
    brand: "Puma",
    product_name: "Velocity Nitro 2",
    category: "Running",
    subcategory: "Neutral",
    color: "Ultra Blue/Puma White",
    color_hex: "#0066CC",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 130.00,
    sale_price: 104.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 54,
    condition: "new",
    material: "Engineered Mesh/NITRO Foam",
    weight_oz: 9.3,
    description: "Everyday versatility with NITRO foam. The Velocity Nitro 2 is your daily trainer with responsive cushioning and reliable grip.",
    short_description: "Versatile NITRO daily trainer",
    final_url: "https://puma.com/us/en/velocity-nitro-2/PM-VELN2-002-BLU-10",
    image_url: "https://puma.com/media/velocity-nitro-2-blue.jpg",
    additional_images: "https://puma.com/media/velocity-nitro-2-blue-2.jpg",
    tags: "sale,nitro,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 1.8,
  },

  // ============================================
  // PUMA - Lifestyle
  // ============================================
  {
    sku: "PM-SUED-010-BLK-10",
    product_id: "PM-SUED-010",
    gtin: "202501235001",
    brand: "Puma",
    product_name: "Suede Classic XXI",
    category: "Lifestyle",
    subcategory: "Heritage",
    color: "Puma Black/Puma White",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 75.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 92,
    condition: "new",
    material: "Suede/Rubber",
    weight_oz: 12.0,
    description: "The legend continues. The Suede Classic XXI honors the iconic 1968 design with premium suede and heritage styling.",
    short_description: "Iconic suede heritage sneaker",
    final_url: "https://puma.com/us/en/suede-classic-xxi/PM-SUED-010-BLK-10",
    image_url: "https://puma.com/media/suede-classic-black.jpg",
    additional_images: "https://puma.com/media/suede-classic-black-2.jpg",
    tags: "icon,heritage,classic",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "PM-RSX-011-WHT-10",
    product_id: "PM-RSX-011",
    gtin: "202501235101",
    brand: "Puma",
    product_name: "RS-X",
    category: "Lifestyle",
    subcategory: "Originals",
    color: "Puma White/Puma Black",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 110.00,
    sale_price: 88.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 45,
    condition: "new",
    material: "Mesh/Leather/Running System",
    weight_oz: 13.5,
    description: "Bold, chunky, unapologetic. The RS-X reinvents the running system for street style with exaggerated proportions and retro vibes.",
    short_description: "Chunky retro runner, bold style",
    final_url: "https://puma.com/us/en/rs-x/PM-RSX-011-WHT-10",
    image_url: "https://puma.com/media/rs-x-white.jpg",
    additional_images: "https://puma.com/media/rs-x-white-2.jpg",
    tags: "sale,retro,chunky,streetwear",
    age_group: "adult",
    shipping_weight_lb: 2.1,
  },

  // ============================================
  // UNDER ARMOUR - Training
  // ============================================
  {
    sku: "UA-PROJ5-001-BLK-10",
    product_id: "UA-PROJ5-001",
    gtin: "203501234001",
    brand: "Under Armour",
    product_name: "Project Rock 5",
    category: "Training",
    subcategory: "CrossFit",
    color: "Black/Pitch Grey",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 41,
    condition: "new",
    material: "Engineered Mesh/TriBase",
    weight_oz: 13.2,
    description: "Train with The Rock. The Project Rock 5 features TriBase outsole for ground contact and Micro G cushioning for explosive movements.",
    short_description: "Dwayne Johnson's training shoe",
    final_url: "https://ua.com/en-us/project-rock-5/UA-PROJ5-001-BLK-10",
    image_url: "https://ua.com/media/project-rock-5-black.jpg",
    additional_images: "https://ua.com/media/project-rock-5-black-2.jpg",
    tags: "training,signature,crossfit",
    age_group: "adult",
    shipping_weight_lb: 2.1,
  },
  {
    sku: "UA-TRIB4-002-GRY-10",
    product_id: "UA-TRIB4-002",
    gtin: "203501234101",
    brand: "Under Armour",
    product_name: "TriBase Reign 4",
    category: "Training",
    subcategory: "CrossFit",
    color: "Pitch Grey/Black",
    color_hex: "#4A4A4A",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: 119.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 33,
    condition: "new",
    material: "Engineered Mesh/TriBase",
    weight_oz: 11.5,
    description: "Ground contact for better lifting. The TriBase Reign 4 maximizes floor contact with a low, flat heel for stable lifts.",
    short_description: "Stable training platform",
    final_url: "https://ua.com/en-us/tribase-reign-4/UA-TRIB4-002-GRY-10",
    image_url: "https://ua.com/media/tribase-reign-4-grey.jpg",
    additional_images: "https://ua.com/media/tribase-reign-4-grey-2.jpg",
    tags: "sale,training,crossfit,weightlifting",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },

  // ============================================
  // UNDER ARMOUR - Running
  // ============================================
  {
    sku: "UA-HOVR3-003-BLK-10",
    product_id: "UA-HOVR3-003",
    gtin: "203501234201",
    brand: "Under Armour",
    product_name: "HOVR Machina 3",
    category: "Running",
    subcategory: "Road Running",
    color: "Black/Jet Grey",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 160.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 38,
    condition: "new",
    material: "Warp Upper/HOVR Foam",
    weight_oz: 10.4,
    description: "Zero gravity feel. The HOVR Machina 3 provides energy return and connected coaching through the UA MapMyRun app.",
    short_description: "Connected running with HOVR cushion",
    final_url: "https://ua.com/en-us/hovr-machina-3/UA-HOVR3-003-BLK-10",
    image_url: "https://ua.com/media/hovr-machina-3-black.jpg",
    additional_images: "https://ua.com/media/hovr-machina-3-black-2.jpg",
    tags: "connected,hovr,daily-trainer",
    age_group: "adult",
    shipping_weight_lb: 2.0,
  },

  // ============================================
  // REEBOK - Training
  // ============================================
  {
    sku: "RB-NANOX4-001-BLK-10",
    product_id: "RB-NANOX4-001",
    gtin: "204501234001",
    brand: "Reebok",
    product_name: "Nano X4",
    category: "Training",
    subcategory: "CrossFit",
    color: "Core Black/Pure Grey",
    color_hex: "#000000",
    size: "10",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 56,
    condition: "new",
    material: "Flexweave/Rubber",
    weight_oz: 11.6,
    description: "The official shoe of CrossFit. The Nano X4 combines Flexweave upper with a wide toe box and low, stable platform.",
    short_description: "Official CrossFit training shoe",
    final_url: "https://reebok.com/us/nano-x4/RB-NANOX4-001-BLK-10",
    image_url: "https://reebok.com/media/nano-x4-black.jpg",
    additional_images: "https://reebok.com/media/nano-x4-black-2.jpg",
    tags: "crossfit,training,official",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "RB-NANOX4-001-WHT-9",
    product_id: "RB-NANOX4-001",
    gtin: "204501234002",
    brand: "Reebok",
    product_name: "Nano X4",
    category: "Training",
    subcategory: "CrossFit",
    color: "Chalk/Core Black",
    color_hex: "#F5F5F5",
    size: "9",
    size_type: "US",
    gender: "Men",
    price: 140.00,
    sale_price: 112.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 42,
    condition: "new",
    material: "Flexweave/Rubber",
    weight_oz: 11.3,
    description: "The official shoe of CrossFit. The Nano X4 combines Flexweave upper with a wide toe box and low, stable platform.",
    short_description: "Official CrossFit training shoe",
    final_url: "https://reebok.com/us/nano-x4/RB-NANOX4-001-WHT-9",
    image_url: "https://reebok.com/media/nano-x4-white.jpg",
    additional_images: "https://reebok.com/media/nano-x4-white-2.jpg",
    tags: "sale,crossfit,training",
    age_group: "adult",
    shipping_weight_lb: 1.8,
  },

  // ============================================
  // REEBOK - Lifestyle
  // ============================================
  {
    sku: "RB-CLUBC-010-WHT-10",
    product_id: "RB-CLUBC-010",
    gtin: "204501235001",
    brand: "Reebok",
    product_name: "Club C 85",
    category: "Lifestyle",
    subcategory: "Heritage",
    color: "Chalk/Glen Green",
    color_hex: "#F5F5F5",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 85.00,
    sale_price: null,
    currency: "USD",
    in_stock: true,
    stock_qty: 78,
    condition: "new",
    material: "Leather/Rubber",
    weight_oz: 12.2,
    description: "Tennis heritage meets street style. The Club C 85 keeps its clean vintage look with soft leather and classic colorways.",
    short_description: "Clean tennis heritage sneaker",
    final_url: "https://reebok.com/us/club-c-85/RB-CLUBC-010-WHT-10",
    image_url: "https://reebok.com/media/club-c-85-chalk.jpg",
    additional_images: "https://reebok.com/media/club-c-85-chalk-2.jpg",
    tags: "heritage,classic,clean",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
  {
    sku: "RB-CLSLTH-011-WHT-10",
    product_id: "RB-CLSLTH-011",
    gtin: "204501235101",
    brand: "Reebok",
    product_name: "Classic Leather",
    category: "Lifestyle",
    subcategory: "Heritage",
    color: "White/Pure Grey",
    color_hex: "#FFFFFF",
    size: "10",
    size_type: "US",
    gender: "Unisex",
    price: 80.00,
    sale_price: 64.00,
    currency: "USD",
    in_stock: true,
    stock_qty: 65,
    condition: "new",
    material: "Leather/Rubber",
    weight_oz: 11.8,
    description: "The original Reebok icon. The Classic Leather maintains its 80s running heritage with supple leather and timeless styling.",
    short_description: "80s running icon, leather classic",
    final_url: "https://reebok.com/us/classic-leather/RB-CLSLTH-011-WHT-10",
    image_url: "https://reebok.com/media/classic-leather-white.jpg",
    additional_images: "https://reebok.com/media/classic-leather-white-2.jpg",
    tags: "sale,heritage,icon,80s",
    age_group: "adult",
    shipping_weight_lb: 1.9,
  },
];

async function seed() {
  console.log("Seeding database...\n");

  // Clear existing data (in reverse order of dependencies)
  console.log("Clearing existing data...");
  await db.delete(schema.creativeTemplateLinks);
  await db.delete(schema.creativeTags);
  await db.delete(schema.creatives);
  await db.delete(schema.syncRecords);
  await db.delete(schema.generatedCampaigns);
  await db.delete(schema.templateRules);
  await db.delete(schema.rules);
  await db.delete(schema.adTemplates);
  await db.delete(schema.adGroupTemplates);
  await db.delete(schema.campaignTemplates);
  await db.delete(schema.columnMappings);
  await db.delete(schema.dataRows);
  await db.delete(schema.dataSources);
  await db.delete(schema.oauthTokens);
  await db.delete(schema.adAccounts);

  // ============================================
  // 1. DATA SOURCE - Demo Catalogue Footwear
  // ============================================
  console.log("Seeding data source...");
  await db.insert(schema.dataSources).values([
    {
      id: uuids.dataSource1,
      name: "demo catalogue footwear",
      type: "csv",
      config: {
        originalFileName: "athletic_footwear_catalog.csv",
        encoding: "utf-8",
        delimiter: ",",
        hasHeader: true,
      },
      createdAt: new Date("2025-01-10T09:00:00Z"),
      updatedAt: new Date("2025-01-15T14:30:00Z"),
    },
  ]);

  // ============================================
  // 2. DATA ROWS
  // ============================================
  console.log(`Seeding data rows (${demoCatalogueFootwear.length} products)...`);
  const dataRowValues = demoCatalogueFootwear.map((data, index) => ({
    id: dataRowUuid(index),
    dataSourceId: uuids.dataSource1,
    rowIndex: index,
    rowData: data,
  }));
  await db.insert(schema.dataRows).values(dataRowValues);

  // ============================================
  // 3. COLUMN MAPPINGS
  // ============================================
  console.log("Seeding column mappings...");
  await db.insert(schema.columnMappings).values([
    { dataSourceId: uuids.dataSource1, sourceColumn: "sku", normalizedName: "sku", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "product_id", normalizedName: "product_id", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "gtin", normalizedName: "gtin", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "brand", normalizedName: "brand", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "product_name", normalizedName: "product_name", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "category", normalizedName: "category", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "subcategory", normalizedName: "subcategory", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "color", normalizedName: "color", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "color_hex", normalizedName: "color_hex", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "size", normalizedName: "size", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "size_type", normalizedName: "size_type", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "gender", normalizedName: "gender", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "price", normalizedName: "price", dataType: "number" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "sale_price", normalizedName: "sale_price", dataType: "number" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "currency", normalizedName: "currency", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "in_stock", normalizedName: "in_stock", dataType: "boolean" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "stock_qty", normalizedName: "stock_qty", dataType: "number" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "condition", normalizedName: "condition", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "material", normalizedName: "material", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "weight_oz", normalizedName: "weight_oz", dataType: "number" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "description", normalizedName: "description", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "short_description", normalizedName: "short_description", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "final_url", normalizedName: "final_url", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "image_url", normalizedName: "image_url", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "additional_images", normalizedName: "additional_images", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "tags", normalizedName: "tags", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "age_group", normalizedName: "age_group", dataType: "string" },
    { dataSourceId: uuids.dataSource1, sourceColumn: "shipping_weight_lb", normalizedName: "shipping_weight_lb", dataType: "number" },
  ]);

  // Count unique values for summary
  const brands = [...new Set(demoCatalogueFootwear.map(p => p.brand))];
  const categories = [...new Set(demoCatalogueFootwear.map(p => p.category))];
  const products = [...new Set(demoCatalogueFootwear.map(p => p.product_id))];

  console.log("\nSeed completed successfully!");
  console.log("\nSeeded data summary:");
  console.log("  - 1 data source: demo catalogue footwear");
  console.log(`  - ${demoCatalogueFootwear.length} SKU variants`);
  console.log(`  - ${products.length} unique products`);
  console.log(`  - ${brands.length} brands: ${brands.join(", ")}`);
  console.log(`  - ${categories.length} categories: ${categories.join(", ")}`);
  console.log("  - 28 column mappings");

  await client.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
